### ISSUE TITLE
Docker Metrics Support for Mac

### ISSUE THREAD

**Issue by yassermohamed81** [nosqlbench/nosqlbench#109]
**Describe the bug**
I am trying to execute the --docker-metrics on mac and it is failing with the below error.
It seems a permission issue with the creation of the Prometheus directory and files.

ymohamed-rmbp15:nosqlbench yassermohamed$ java -jar nb.jar run type=cql yaml=conf/test_intuit.yaml tags=phase:write-credentials cycles=0..2 cyclerate=10 --progress console:1s --docker-metrics
Exception in thread "main" com.github.dockerjava.api.exception.BadRequestException: {"message":"OCI runtime create failed: container_linux.go:349: starting container process caused \"chdir to cwd (\\\"/prometheus\\\") set in config.json failed: permission denied\": unknown"}
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:283)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at io.nosqlbench.engine.docker.DockerHelper.startDocker(DockerHelper.java:141)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startPrometheus(DockerMetricsManager.java:114)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startMetrics(DockerMetricsManager.java:44)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:136)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:45)
ymohamed-rmbp15:nosqlbench yassermohamed$ ls -ltrah /Users/yassermohamed/.nosqlbench/prometheus
ls: prometheus: Permission denied 

**To Reproduce**
ymohamed-rmbp15:nosqlbench yassermohamed$ java -jar nb.jar run type=cql yaml=conf/test_intuit.yaml tags=phase:write-credentials cycles=0..2 cyclerate=10 --progress console:1s --docker-metrics
Exception in thread "main" com.github.dockerjava.api.exception.BadRequestException: {"message":"OCI runtime create failed: container_linux.go:349: starting container process caused \"chdir to cwd (\\\"/prometheus\\\") set in config.json failed: permission denied\": unknown"}
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:283)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at io.nosqlbench.engine.docker.DockerHelper.startDocker(DockerHelper.java:141)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startPrometheus(DockerMetricsManager.java:114)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startMetrics(DockerMetricsManager.java:44)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:136)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:45)
ymohamed-rmbp15:nosqlbench yassermohamed$ ls -ltrah /Users/yassermohamed/.nosqlbench/prometheus
ls: prometheus: Permission denied

**What was Expected**
Docker Metrics available for Mac.

**Comment by jshook** [comment]
@phact @weideng1 This is one of the bug reports that caused the warning details on the main README. If we can hammer out the usability issues for Mac, we'll take that qualifier off the description and encourage Mac users to test it out.

**Comment by phact** [comment]
Great, we'll check it out tomorrow

**Comment by phact** [comment]
@weideng1 this is fixed right?

**Comment by jshook** [comment]
I believe this is fixed. I'll close the issue without further reports, but we can re-open it if we see any hitches.

**Comment by jshook** [comment]
@all-contributors please add @weideng1 for platform, bug reports, bug fixes

**Comment by jshook** [comment]
@all-contributors please add @weideng1 for platform, bug reports, bug fixes
