### ISSUE TITLE
Keyspace "baselines" does not exist during nb run

### ISSUE THREAD

**Issue by tanvp112** [nosqlbench/nosqlbench#1104]
**Describe the bug**
nb run failed with keyspace "baselines" does not exist.

**To Reproduce**
1. Installed apache cassandra 4.1 and tested using bin/cqlsh with no issue.
2. java -jar nb5.jar cql-iot host=a.b.c.d localdc=datacenter1

**What was Expected**
nb to complete the benchmark test.

**Additional context**
Centos 8, nosqlbench version 5.17.1

**Screenshots, if applicable**
The test failed with multiple exceptions complaining "keyspace baselines does not exit", "table iot does not exist". The run command should have started with [schema](https://github.com/nosqlbench/nosqlbench/blob/main/adapter-cqld4/src/main/resources/activities/baselines/cql-iot.yaml#L7), follow by rampup and main. Apparently, the schema block was not executed. Tested with cql-keyvalue with same error.

Can anyone shade a light if any configuration/step is missing here?

Reference: https://docs.nosqlbench.io/getting-started/02-scenarios/

**Comment by jshook** [comment]
I believe this looks correct. I'm verifying this locally.

**Comment by jshook** [comment]
@tanvp112 I found a syntax error in the cql-keyvalue workload, but the cql-iot one works fine. Is it possible that you were seeing this with the cql-keyvalue workload instead?

**Comment by tanvp112** [comment]
Here's the detail exception dump when run with *cql-iot*. The apache cassandra 4.1 in used is a stock installation. Do you need to change any setting in cassandra.yaml for your test?

```
[user@ip apache-cassandra-4.1.0]$ java -jar bin/nb5.jar cql-iot host=localhost localdc=datacenter1
    5812 ERROR [scenarios:001] SCENARIO     Error in scenario, shutting down. (javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]'))
    5891 WARN  [main] NBCLI        executions: 1 scenarios, 0 normal, 1 errored
    5907 ERROR [main] ERRORHANDLER Error from driver or included library: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:335)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.runScenario(Scenario.java:269)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:406)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:63)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
        at io.nosqlbench.engine.api.activityimpl.SimpleActivity.createOpSourceFromParsedOps(SimpleActivity.java:523)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:122)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
        at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
        at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:45)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:84)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:135)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:116)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:145)
        at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.run(PolyglotScenarioController.java:57)
        at <js>.:program(<eval>:1)
        at org.graalvm.polyglot.Context.eval(Context.java:399)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:478)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:420)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
        at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:311)
        ... 7 more
Caused by: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
        at io.nosqlbench.engine.api.activityimpl.SimpleActivity.createOpSourceFromParsedOps(SimpleActivity.java:523)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:122)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
        at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
        at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:45)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:84)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:135)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:116)
        at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:145)
        at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.run(PolyglotScenarioController.java:57)
        at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:350)
        at com.oracle.truffle.host.GuestToHostCodeCache$1.executeImpl(GuestToHostCodeCache.java:96)
        at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:177)
        at com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
        at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:386)
        at com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
        at com.oracle.truffle.host.HostExecuteNode.doOverloadedCached(HostExecuteNode.java:288)
        at com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:241)
        at com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:97)
        at com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:454)
        at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2696)
        at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2678)
        at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1534)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:306)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:740)
        at com.oracle.truffle.js.nodes.JavaScriptNode.executeVoid(JavaScriptNode.java:192)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
        at com.oracle.truffle.api.impl.DefaultBlockNode.executeGeneric(DefaultBlockNode.java:63)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:88)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
        at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:245)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
        at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1470)
        at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
        ... 12 more
Caused by: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
        at io.nosqlbench.adapter.cqld4.opdispensers.Cqld4PreparedStmtDispenser.createStmtFunc(Cqld4PreparedStmtDispenser.java:71)
        at io.nosqlbench.adapter.cqld4.opdispensers.Cqld4PreparedStmtDispenser.<init>(Cqld4PreparedStmtDispenser.java:55)
        at io.nosqlbench.adapter.cqld4.opmappers.CqlD4PreparedStmtMapper.apply(CqlD4PreparedStmtMapper.java:73)
        at io.nosqlbench.adapter.cqld4.opmappers.Cqld4CoreOpMapper.apply(Cqld4CoreOpMapper.java:74)
        at io.nosqlbench.engine.api.activityimpl.SimpleActivity.createOpSourceFromParsedOps(SimpleActivity.java:503)
        ... 56 more
    5930 ERROR [main] ERRORHANDLER cause (see stack trace for details):io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:cql-iot]  cause: OpConfigError:Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]') Error while configuring op from workload template: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: keyspace baselines does not exist( for statement 'parsed: [truncate table baselines.iot;
]')
```

Keyspace "baselines" was not created:

```
[user@ip apache-cassandra-4.1.0]$ bin/cqlsh
Connected to Test Cluster at 127.0.0.1:9042
[cqlsh 6.1.0 | Cassandra 4.1.0 | CQL spec 3.4.6 | Native protocol v5]
Use HELP for help.
cqlsh> desc keyspaces;

system       system_distributed  system_traces  system_virtual_schema
system_auth  system_schema       system_views

cqlsh>
```

nosqlbench version:

```
[user@ipapache-cassandra-4.1.0]$ java -jar bin/nb5.jar --version
5.17.1-release
```
