### ISSUE TITLE
Feature: Implement connection retry logic in JDBC driver

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#1174]
**What is the ideal scenario for using this feature?**
During rolling upgrades, the PostgreSQL-compatible databases issues `08006 An I/O error occurred while sending to the backend`. So the application has to do the following:
Upon receiving a connection error, your application must handle the result of a previously open transaction as unknown.
A connection retry loop should:
1. Close the current connection.
2. Open a new connection. This will be routed to a non-draining node.
3. Reissue the transaction on the new connection.
4. Repeat while the connection error persists and the retry count has not exceeded a configured maximum.

**Is your feature request related to a problem? Please describe.**
Today, when rolling upgrades/node shutdown happens, we get errors such as the following:
```
2023-03-16 18:25:42,691 [pgsqltab_default_rampup:3686] ERROR: ERROR: [ state => 08006, cause => java.net.SocketException: Connection or outbound has closed, message => An I/O error occurred while sending to the backend. ]
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:383) ~[nb5.jar:?]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[nb5.jar:?]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[nb5.jar:?]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333) ~[nb5.jar:?]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319) ~[nb5.jar:?]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295) ~[nb5.jar:?]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290) ~[nb5.jar:?]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[nb5.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[nb5.jar:?]
	at io.nosqlbench.adapter.jdbc.optypes.JDBCExecuteOp.run(JDBCExecuteOp.java:37) ~[nb5.jar:?]
	at io.nosqlbench.engine.api.activityimpl.uniform.actions.StandardAction.runCycle(StandardAction.java:98) ~[nb5.jar:?]
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:393) ~[nb5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.SocketException: Connection or outbound has closed
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1291) ~[?:?]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[?:?]
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95) ~[?:?]
	at org.postgresql.core.PGStream.sendChar(PGStream.java:346) ~[nb5.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.sendSync(QueryExecutorImpl.java:1526) ~[nb5.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1455) ~[nb5.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481) ~[nb5.jar:?]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:348) ~[nb5.jar:?]
	... 14 more
```

**Would you like to help implementing or testing it?**
Ideate/Testing

**Additional context**; n/a

**Comment by msmygit** [comment]
An idea is to leverage the NB's generic error retry mechanism. For e.g.
```
errors='SocketException:08006:retry;counter'
```
This will invoke the default `maxtries=10` for all `SocketException`, and assign an error code of `08006`. For non-matching errors, it'd simply count them to report at the end.

**Comment by jshook** [comment]
I think this should already work, since the error handlers wrap all operations and allow for retry to be specified. The example above should work, and the error code should not be needed. Like this:
`errors=SocketException:retry,counter`.

This simply means that any exception with the base name of SocketException gets routed to an error handler that:
1. Flags the response as a retryable error
2. Counts the occurrences of such

When the error is flagged as retryable here, then nb will automatically retry it up to the retries limit which is 10 by default.

@msmygit I don't think there is anything to do here but validate that this work. Do you agree?
