### ISSUE TITLE
nb5 commands are failing although they ran successfully a few months prior

### ISSUE THREAD

**Issue by atrilok** [nosqlbench/nosqlbench#1235]
Describe the bug

I am using the following nosqlbench command to create an Astra DB  table and insert data into it:

`/Users/adityatrilok/Documents/Java17/jdk-17.0.5.jdk/Contents/Home/bin/java -jar nb5.jar workloads/category astra.schema --show-stacktraces \
                        userfile=/Users/adityatrilok/Documents/nb5/workloads/username_rmc  \
                        passfile=/Users/adityatrilok/Documents/nb5/workloads/secret_rmc  \
                        scb=/Users/adityatrilok/Documents/nb5/workloads/secure-connect-coaction-db.zip \
                        keyspace=coaction_ks`

The version of nb5  I am using is: 

4.17.30

But I am getting the following error

```
 3151 ERROR [scenarios:001] SCENARIO     Error in scenario, shutting down. (javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present)
    3178 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:149)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:114)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:72)
	at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:476)
	at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:109)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:91)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:304)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:359)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
	at io.nosqlbench.engine.api.activityimpl.SimpleActivity.createOpSourceFromParsedOps(SimpleActivity.java:506)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:115)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:59)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.getActivityExecutor(ScenarioController.java:337)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:123)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:104)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:138)
	at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:56)
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:379)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:400)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:284)
	... 6 more
Caused by: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
	at io.nosqlbench.engine.api.activityimpl.SimpleActivity.createOpSourceFromParsedOps(SimpleActivity.java:506)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:115)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:59)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.getActivityExecutor(ScenarioController.java:337)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:123)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:104)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:138)
	at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:56)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:333)
	at com.oracle.truffle.host.GuestToHostCodeCache$1.executeImpl(GuestToHostCodeCache.java:98)
	at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:81)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:142)
	at com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:107)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:364)
	at com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
	at com.oracle.truffle.host.HostExecuteNode.doOverloadedCached(HostExecuteNode.java:288)
	at com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:240)
	at com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:96)
	at com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:451)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2695)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2677)
	at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8138)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1510)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:304)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:250)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:728)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:163)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:86)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:317)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:118)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:150)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:230)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1219)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:62)
	... 11 more
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at io.nosqlbench.adapter.cqld4.Cqld4Space.createSession(Cqld4Space.java:142)
	at io.nosqlbench.adapter.cqld4.Cqld4Space.<init>(Cqld4Space.java:55)
	at io.nosqlbench.adapter.cqld4.Cqld4DriverAdapter.lambda$getSpaceInitializer$0(Cqld4DriverAdapter.java:50)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.nosqlbench.engine.api.activityimpl.uniform.DriverSpaceCache.get(DriverSpaceCache.java:64)
	at io.nosqlbench.adapter.cqld4.opmappers.Cqld4CoreOpMapper.lambda$apply$0(Cqld4CoreOpMapper.java:63)
	at io.nosqlbench.adapter.cqld4.opdispensers.Cqld4PreparedStmtDispenser.createStmtFunc(Cqld4PreparedStmtDispenser.java:67)
	at io.nosqlbench.adapter.cqld4.opdispensers.Cqld4PreparedStmtDispenser.<init>(Cqld4PreparedStmtDispenser.java:55)
	at io.nosqlbench.adapter.cqld4.opmappers.CqlD4PreparedStmtMapper.apply(CqlD4PreparedStmtMapper.java:73)
	at io.nosqlbench.adapter.cqld4.opmappers.Cqld4CoreOpMapper.apply(Cqld4CoreOpMapper.java:74)
	at io.nosqlbench.engine.api.activityimpl.SimpleActivity.createOpSourceFromParsedOps(SimpleActivity.java:496)
	... 53 more
    3185 ERROR [main] ERRORHANDLER cause (see stack trace for details):javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:workloads/category]  cause: NoSuchElementException:No value present No value present
    3187 WARN  [Thread-2] SCENARIO     Scenario was interrupted by process exit, shutting down
```

To Reproduce

1. Ensure the 'yaml' file is within the folder called 'workloads' as shown below:
 
`workloads/category`

The actual full path is '/Users/adityatrilok/Documents/nb5/workloads/category.yaml'

2. Pass the path to the scb, and for userfile, ensure that the client_id for a role with the correct permissions are being used. Admin role is good. 

3. For passfile, pass the value of the corresponding client_secret 

Please find the yaml file below for your reference:

```description: A tabular workload with partitions, clusters, and data fields

scenarios:
  astra:
    schema: run driver=cql tags==block:schema-astra threads==1 cycles==UNDEF
    main: run driver=cql tags==block:main-write cycles===1000000 threads=50 cyclerate=4000

bindings:

   # for write
     parent_id_write: AddHashRange(1,10000000);Mod(10000000L); Hash(); ToUUID();
     category_id_write: AddHashRange(1,10000000);Mod(10000000L); Hash(); ToUUID();
     name_write: Combinations('T;S;h;i;r;t')
     image_write: JoinTemplate('.',Combinations('b;h;0-9;0-9;0-9'),WeightedStrings('png:1;gif:1;jpeg:1'))
     products_write:  List(HashRange(1,<<list-count-contributors:5>>),Combinations('XL;M')) ->java.util.List


blocks:
  schema-astra:
    params:
      prepared: false
    ops:
      create-table: |
        CREATE TABLE if not exists <<keyspace:baselines>>.<<table:category>> (
         parent_id UUID,
         category_id UUID,
         name TEXT,
         image TEXT,
         products LIST<TEXT>,
         PRIMARY KEY (parent_id,category_id)
        );

  main-write:
    params:
      ratio: 5
      cl: <<write_cl:LOCAL_QUORUM>>
    ops:
      my-write: |
                    insert into <<keyspace:baselines>>.<<table:category>>
                    (parent_id, category_id, name, image, products)
                    values ({parent_id_write},{category_id_write},{name_write},{image_write},{products_write})
```

What was Expected

The command below worked as is a few months ago:
```
/Users/adityatrilok/Documents/Java17/jdk-17.0.5.jdk/Contents/Home/bin/java -jar nb5.jar workloads/category astra.schema --show-stacktraces \
                        userfile=/Users/adityatrilok/Documents/nb5/workloads/username_rmc  \
                        passfile=/Users/adityatrilok/Documents/nb5/workloads/secret_rmc  \
                        scb=/Users/adityatrilok/Documents/nb5/workloads/secure-connect-coaction-db.zip \
                        keyspace=coaction_ks
```

Additional context
I am running it on my Macbook pro running MacOS Monterrey and an Apple M1 chip

**Comment by MikeYaacoubStax** [comment]
Hello! 

This might not help much but fwiw I just ran the exact same command with the exact same workload on my machine with nb5 version 4.17.26:

`./nb5 category.yaml astra.schema  userfile=username_rmc  passfile=secret_rmc scb=secure-connect-testingbug.zip keyspace=coaction_ks`
--->
![image](https://user-images.githubusercontent.com/117678633/235248597-4e7b7a96-a6d2-43ed-b1b7-08a864a6eb12.png)

`./nb5 --version`
--->
4.17.26

Had no issues running it.

**Comment by jshook** [comment]
@atrilok Can you let us know if this is still unresolved?

**Comment by atrilok** [comment]
Yes, this is still unresolved.



Aditya Trilok

c. +1 647 613 2660

w. www.datastax.com

<https://urldefense.com/v3/__https://www.facebook.com/datastax__;!!PbtH5S7Ebw!ZaRJ0wAGYmNepFqLjuzJNy_fxBsf8cfMENoumpE9aPpIf2lS2GjXypQqEbg0X5rlw2lO8bOEtp56DB-aaBW1$>
<https://twitter.com/datastax>
<https://urldefense.com/v3/__https://www.linkedin.com/company/datastax/__;!!PbtH5S7Ebw!ZaRJ0wAGYmNepFqLjuzJNy_fxBsf8cfMENoumpE9aPpIf2lS2GjXypQqEbg0X5rlw2lO8bOEtp56DJUSH6Xt$>
<https://github.com/datastax/>


<https://www.datastax.com/lp/astra-registration>

**Comment by jshook** [comment]
@atrilok Can you run this using a newer version, like [5.17.3](https://github.com/nosqlbench/nosqlbench/releases/tag/5.17.3-release) ?

**Comment by atrilok** [comment]
@Jonathan Shook ***@***.***> Yes, the version 5.17.3 is working
fine. Thank you!



Aditya Trilok

c. +1 647 613 2660

w. www.datastax.com

<https://urldefense.com/v3/__https://www.facebook.com/datastax__;!!PbtH5S7Ebw!ZaRJ0wAGYmNepFqLjuzJNy_fxBsf8cfMENoumpE9aPpIf2lS2GjXypQqEbg0X5rlw2lO8bOEtp56DB-aaBW1$>
<https://twitter.com/datastax>
<https://urldefense.com/v3/__https://www.linkedin.com/company/datastax/__;!!PbtH5S7Ebw!ZaRJ0wAGYmNepFqLjuzJNy_fxBsf8cfMENoumpE9aPpIf2lS2GjXypQqEbg0X5rlw2lO8bOEtp56DJUSH6Xt$>
<https://github.com/datastax/>


<https://www.datastax.com/lp/astra-registration>

**Comment by jshook** [comment]
Thanks!
