### ISSUE TITLE
Parent child labeling conflict on NB5 Pulsar adapter

### ISSUE THREAD

**Issue by yabinmeng** [nosqlbench/nosqlbench#1283]
**Describe the bug**
Tried to run NB5 Pulsar message publishing using the latest code base and I ran into the following error
```
Caused by: java.lang.RuntimeException: Can't overlap label keys (for instance name) between parent and child elements. parent:{name=PulsarBaseOpDispenser}, child:{name=err_msg_oos}
	at io.nosqlbench.api.config.MapLabels.lambda$new$0(MapLabels.java:34)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at io.nosqlbench.api.config.MapLabels.<init>(MapLabels.java:32)
	at io.nosqlbench.api.config.MapLabels.and(MapLabels.java:100)
	at io.nosqlbench.api.engine.metrics.ActivityMetrics.counter(ActivityMetrics.java:160)
	at io.nosqlbench.adapter.pulsar.util.PulsarAdapterMetrics.initPulsarAdapterInstrumentation(PulsarAdapterMetrics.java:70)
	at io.nosqlbench.adapter.pulsar.dispensers.PulsarBaseOpDispenser.<init>(PulsarBaseOpDispenser.java:83)
```

**Additional context**
According to the following code log (https://github.com/nosqlbench/nosqlbench/blob/4de2aa67d63a642c67a0ab3fc6470a5f880f857d/nb-api/src/main/java/io/nosqlbench/api/config/MapLabels.java#L29), NB5 complains if both the parent and the child has the same label key which in this case is "name". The "name" label key is added by the NB engine, not by the adapter. I'm not really sure if this is the right way to fail the NB execution.

**Comment by jeffbanks** [comment]
@jshook as reference, I believe this may be related to the space name inclusion for a scoped metric name.

For example:
```java
public String getName() {
        return "http"+("default".equals(this.space.getSpaceName())?"": '-' + space.getSpaceName());
    }
```

**Comment by jshook** [comment]
@yabinmeng Do you think this is fully addressed in the latest code?
