### ISSUE TITLE
Clearer message when attempting to use bindings with simple statements

### ISSUE THREAD

**Issue by alicel** [nosqlbench/nosqlbench#141]
Attempting to use bindings in a CQL statement that is not a prepared statement results in a failure, which is fair enough. However, the error message currently displayed comes directly from the driver and may not be clear enough.

Example:
```
  - name: myblock
    tags:
      phase: myphase 
    params:
      prepared: false
    statements:
    - store_some_value: |
        insert into myks.mytable (part_key, clust_c, value1)
        values ({part_k_binding}, {clust_c_binding}, {value1_binding});
       rowoperators: print
       tags:
         name: store_some_value
```

Results in this exception:

```
16:17:09.533 [kv2-backup:001] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.RuntimeException: com.datastax.driver.core.exceptions.InvalidQueryException: there were 3 markers(?) in CQL but 0 bound variables
java.lang.RuntimeException: com.datastax.driver.core.exceptions.InvalidQueryException: there were 1 markers(?) in CQL but 0 bound variables
	at io.nosqlbench.activitytype.cql.errorhandling.NBCycleErrorHandler.handleError(NBCycleErrorHandler.java:74)
	at io.nosqlbench.activitytype.cql.errorhandling.NBCycleErrorHandler.handleError(NBCycleErrorHandler.java:95)
	at io.nosqlbench.activitytype.cql.errorhandling.NBCycleErrorHandler.handleError(NBCycleErrorHandler.java:42)
	at io.nosqlbench.engine.api.activityapi.errorhandling.HashedErrorHandler.handleError(HashedErrorHandler.java:268)
	at io.nosqlbench.activitytype.cql.errorhandling.HashedCQLErrorHandler.handleError(HashedCQLErrorHandler.java:70)
	at io.nosqlbench.activitytype.cql.errorhandling.HashedCQLErrorHandler.handleError(HashedCQLErrorHandler.java:14)
	at io.nosqlbench.engine.api.activityapi.errorhandling.CycleErrorHandler.handleError(CycleErrorHandler.java:23)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:225)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:72)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: there were 3 markers(?) in CQL but 0 bound variables
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:41)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:26)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:284)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:132)
	... 5 common frames omitted
```

**Comment by jshook** [comment]
@alicel, for this specific error, can you suggest an alternate way of presenting it that would work better? The original error comes directly from the driver, but the stack trace seems a distraction.

Maybe we present the original error, and then one line from the stack showing where it occured?

**Comment by jshook** [comment]
The CQL driver error messaging has been improved significantly since this was filed.

**Comment by jshook** [comment]
@all-contributors please add @alicel for bug
