### ISSUE TITLE
Missing binding function with vague error

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1469]
```
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
    at io.nosqlbench.virtdata.core.bindings.VirtDataFunctionResolver.resolveFunctions(VirtDataFunctionResolver.java:134)
    at io.nosqlbench.virtdata.core.bindings.VirtDataLibraries.resolveFunctions(VirtDataLibraries.java:52)
    at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolve(VirtDataComposer.java:143)
    at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveDiagnosticFunctionFlow(VirtDataComposer.java:173)
    at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveFunctionFlow(VirtDataComposer.java:222)
    at io.nosqlbench.virtdata.core.bindings.VirtData.getOptionalMapper(VirtData.java:107)
    at io.nosqlbench.virtdata.core.templates.StringCompositor.lambda$new$1(StringCompositor.java:52)
    at java.base/java.util.HashMap.forEach(HashMap.java:1421)
    at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:51)
    at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:73)
    at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
    at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
    at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:142)
    at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
    at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:123)
    at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:113)
    at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:352)
    at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:92)
    at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
    at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:38)
    at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
```

**Comment by jshook** [comment]
The error message that came from this was improved. There may be a separate issue with absolute paths.
