### ISSUE TITLE
--docker-metrics Grafana version has not been pulled

### ISSUE THREAD

**Issue by phact** [nosqlbench/nosqlbench#157]
**Describe the bug**
Docker automation should pull the docker versions it needs

**To Reproduce**
On a host that has never pulled grafana:7.01 run with --docker-metrics

**What was Expected**

Containers should get pulled and configured

**Additional context**
```
tato@wezn:$ ./nb ... --docker-metrics
Exception in thread "main" com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: grafana/grafana:7.0.1"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:129)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
	at io.nosqlbench.engine.docker.DockerHelper.startDocker(DockerHelper.java:125)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startGrafana(DockerMetricsManager.java:83)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startMetrics(DockerMetricsManager.java:50)
```
**Screenshots, if applicable**

**Comment by phact** [comment]
Workaround `docker pull grafana/grafana:7.0.1` and try again.

**Comment by dave2wave** [comment]
As we work on new container logic we need to review what are minimal requirements are for the grafana docker image. We are a few versions past 7.0.1

**Comment by jshook** [comment]
This is superseded by a new approach to be documented in a separate issue.
