### ISSUE TITLE
ERRORHANDLER internal error: Error while waiting for activity completion:null

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#1620]
**Describe the bug**
When a scenario errors, we get this at the very end,

```
4518 INFO  [main] NBCLI        executions: 1 scenarios, 0 normal, 1 errored
    4518 WARN  [main] NBCLI        executions: 1 scenarios, 0 normal, 1 errored
    4521 ERROR [main] ERRORHANDLER internal error: Error while waiting for activity completion:null
java.lang.RuntimeException: Error while waiting for activity completion:null
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityExecutor.awaitActivityCompletion(ActivityExecutor.java:510)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityExecutor.call(ActivityExecutor.java:420)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityExecutor.call(ActivityExecutor.java:60)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Error while waiting for activity completion:null
```

**Additional context**
OS: Linux (ubuntu 18.04)
version info (`15.17.5-preview`)

**Comment by jshook** [comment]
This is a bug, because something stopped the activity and the error was not captured in a thread-safe way.
