### ISSUE TITLE
jdbc driver can't used

### ISSUE THREAD

**Issue by zhegemingzimeibanquan** [nosqlbench/nosqlbench#1629]
### jdbc driver can't used

**To Reproduce**
### run the command
i'm sure the connection info is ok
**bin/nb5 start driver= yaml=workload/jdbc/jdbc_gp.yaml  threads=auto url='jdbc:postgresql://****:5432/press_test' databaseName=press_test user='****' password='****'**

    2903 WARN  [scenarios:001] ActivityDef  Auto replacing deprecated activity param 'yaml=workload/jdbc/jdbc_gp.yaml' with new 'workload=workload/jdbc/jdbc_gp.yaml'.
    3007 ERROR [scenarios:001] SCENARIO     Error in scenario, shutting down. (javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null)
    3035 WARN  [main] NBCLI        executions: 1 scenarios, 0 normal, 1 errored
    3039 ERROR [main] ERRORHANDLER Error from driver or included library: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null
java.lang.RuntimeException: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:335)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.runScenario(Scenario.java:269)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:406)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null
	at io.nosqlbench.engine.api.activityconfig.rawyaml.OpsOwner.setOpsFieldByType(OpsOwner.java:105)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.OpsOwner.setFieldsByReflection(OpsOwner.java:56)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsBlock.setFieldsByReflection(RawOpsBlock.java:31)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsDoc.setFieldsByReflection(RawOpsDoc.java:73)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsLoader.parseYaml(RawOpsLoader.java:91)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsLoader.loadString(RawOpsLoader.java:63)
	at io.nosqlbench.engine.api.activityconfig.OpsLoader.loadString(OpsLoader.java:75)
	at io.nosqlbench.engine.api.activityconfig.OpsLoader.loadPath(OpsLoader.java:60)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:63)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:45)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:84)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.start(ScenarioController.java:78)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.start(ScenarioController.java:101)
	at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.start(PolyglotScenarioController.java:106)
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:478)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:420)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:311)
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null
	at io.nosqlbench.engine.api.activityconfig.rawyaml.OpsOwner.setOpsFieldByType(OpsOwner.java:105)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.OpsOwner.setFieldsByReflection(OpsOwner.java:56)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsBlock.setFieldsByReflection(RawOpsBlock.java:31)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsDoc.setFieldsByReflection(RawOpsDoc.java:73)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsLoader.parseYaml(RawOpsLoader.java:91)
	at io.nosqlbench.engine.api.activityconfig.rawyaml.RawOpsLoader.loadString(RawOpsLoader.java:63)
	at io.nosqlbench.engine.api.activityconfig.OpsLoader.loadString(OpsLoader.java:75)
	at io.nosqlbench.engine.api.activityconfig.OpsLoader.loadPath(OpsLoader.java:60)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:63)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:36)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:63)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:45)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:84)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.start(ScenarioController.java:78)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.start(ScenarioController.java:101)
	at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.start(PolyglotScenarioController.java:106)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:350)
	at com.oracle.truffle.host.GuestToHostCodeCache$1.executeImpl(GuestToHostCodeCache.java:96)
	at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:177)
	at com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:386)
	at com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
	at com.oracle.truffle.host.HostExecuteNode.doFixed(HostExecuteNode.java:137)
	at com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:144)
	at com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:97)
	at com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:454)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2696)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2678)
	at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1534)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:306)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:740)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:124)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:43)
	at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:330)
	at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:118)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:88)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:245)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1470)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	... 12 more
    3047 ERROR [main] ERRORHANDLER cause (see stack trace for details):java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null
javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.util.Map$Entry.getValue()" is null

**Comment by jshook** [comment]
The JDBC driver recently had significant updates after being little-used for awhile. It should work better for you now.
