### ISSUE TITLE
Need CQL bindings for frozen<list<float>> column type

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#1793]
**Describe the bug**
CQL column type of `frozen<list<float>>` binding gives NumberFormatException.

**To Reproduce**
Steps to reproduce the behavior using `driver=cql`:
Workload snippet:
```
bindings:
   frozen<list<float>>: ListSizedHashed(HashRange(1,1000),HashRange(0.0,1.0); DoubleToFloat();)
```
CQL Table:
```
col_00026 frozen<list<float>>,
```

<details>
    <summary>Click here to Expand/Collapse Exception Stacktrace</summary>
    ```
    7644 ERROR [scenarios:001] SCENARIO     Error in scenario, shutting down. ({})
javax.script.ScriptException: java.lang.NumberFormatException: For input string: "[0.41664743, 0.0041140798, 0.031210342, 0.3577026, 0.7661032, 0.46911007, 0.54842097, 0.26967052, 0.58288395, 0.22645862, 0.5034224, 0.9049926, 0.23829463, 0.32980722, 0.6761961, 0.6981883, 0.3200009, 0.4490906, 0.12666588, 0.6430993, 0.49963868, 0.31284282, 0.763792, 0.11513454, 0.67092836, 0.93725747, 0.54872674, 0.097864285, 0.7646463, 0.9818316, 0.67528826, 0.679239, 0.2656406, 0.14121564, 0.3102456, 0.6077616, 0.7327927, 0.48506156, 0.18762742, 0.25338155, 0.58579046, 0.063707665, 0.58357996, 0.60465467, 0.04848841, 0.044691086, 0.14575632, 0.041651297, 0.18028255, 0.92257524, 0.44763422, 0.65803826, 0.12804899, 0.70822024, 0.90674514, 0.65545326, 0.11204895, 0.11499816, 0.44230947, 0.5864353, 0.96790296, 0.58148766, 0.93778527, 0.80270666, 0.2831041, 0.10937845, 0.8053076, 0.28792813, 0.50862604, 0.40342772, 0.5568974, 0.02963415, 0.40321782, 0.029187795, 0.4384079, 0.74030435, 0.39401352, 0.993826, 0.039260495, 0.16641535, 0.8459175, 0.015068607, 0.19718032, 0.51955557, 0.27065313, 0.16150884, 0.7809726, 0.51703984, 0.39348963, 0.7283518, 0.6071092, 0.48824468, 0.68459404, 0.24343185, 0.34980676, 0.492753, 0.45056581, 0.28344908, 0.61025333, 0.34652892, 0.017417664, 0.1817564, 0.9689303, 0.6006299, 0.90755016, 0.4539173, 0.40951812, 0.53548676, 0.4688812, 0.76815206, 0.659321, 0.6644502, 0.13146335, 0.6750844, 0.3372118, 0.32972416, 0.6660541, 0.46084377, 0.2129152, 0.7485146, 0.45528877, 0.47468567, 0.31259716, 0.92716926, 0.8958603, 0.28182846, 0.27148324, 0.12159255, 0.75116074, 0.59003747, 0.07221658, 0.9897092, 0.9821176, 0.6505591, 0.57315195, 0.9013027, 0.78542703, 0.5950717, 0.4211729, 0.52863276, 0.7565085, 0.13213058, 0.28531376, 0.22839609, 0.8983835, 0.39091632, 0.71623194, 0.47023162, 0.3615875, 0.2184856, 0.8175504, 0.12303334, 0.27900133, 0.5292291, 0.566849, 0.45339718, 0.08979274, 0.47564128, 0.522547, 0.02864396, 0.5246605, 0.4956322, 0.53097874, 0.25780547, 0.87070465, 0.053854413, 0.30447194, 0.28424934, 0.29209283, 0.8257855, 0.84918666, 0.018738225, 0.30064487, 0.50120825, 0.7836194, 0.48977852, 0.070484295, 0.2786937, 0.7484871, 0.27036792, 0.8279852, 0.7355909, 0.7820941, 0.42583066, 0.80037546, 0.5605368, 0.66835177, 0.33273193, 0.5447857, 0.6558605, 0.6073436, 0.019365942, 0.075855136, 0.45607352, 0.90365696, 0.24260315, 0.6989602, 0.10360575, 0.9031459, 0.7602013, 0.53921854, 0.24418008, 0.9534409, 0.2077292, 0.65588814, 0.544023, 0.011964745, 0.9512949, 0.98649293, 0.7634876, 0.88554984, 0.83256096, 0.44663233, 0.4276707, 0.948232, 0.86184484, 0.18994078, 0.82322, 0.32606173, 0.507698, 0.91296905, 0.640866, 0.40231508, 0.11987478, 0.31411326, 0.86857235, 0.49456894, 0.98898596, 0.48263043, 0.14988042, 0.61491305, 0.33881086, 0.71110433, 0.19185369, 0.98263174, 0.38141716, 0.5309092, 0.56624264, 0.09057603, 0.3373434, 0.22150072, 0.13043882, 0.7747343, 0.75274223, 0.14761584, 0.57620484, 0.42330045, 0.05905397, 0.9144481, 0.73432475, 0.150127, 0.34640664, 0.25937915, 0.97647244, 0.6144487, 0.32702738, 0.4311388, 0.6927873, 0.5464044, 0.55545604, 0.23719904, 0.6912818, 0.6959132, 0.47528782, 0.6001572, 0.6639971, 0.68031275, 0.7648861, 0.57166755, 0.17419398, 0.24202004, 0.91730857, 0.13876812, 0.43690306, 0.5359196, 0.2950771, 0.2817587, 0.55254596, 0.49494272, 0.5608494, 0.7755488, 0.5624231, 0.06292067, 0.8160285, 0.968782, 0.72521937, 0.37803528, 0.93579715, 0.3072157, 0.81407696, 0.18710555, 0.63321847, 0.98953533, 0.43497646, 0.99093974, 0.11155998, 0.13598569, 0.7197043, 0.70945567, 0.9494274, 0.94431424, 0.11880333, 0.43696752, 0.36046597, 0.3510791, 0.4277881, 0.7343808, 0.17351837, 0.2470645, 0.02920208, 0.7804269, 0.940166, 0.39287722, 0.9119309, 0.8727847, 0.1009619, 0.8907118, 0.1870652, 0.37678367, 0.37059155, 0.98690844, 0.48942158, 0.10111245, 0.5524151, 0.96801627, 0.25896445, 0.8310115, 0.03947638, 0.2481636, 0.5569855, 0.33525857, 0.7332102, 0.07834539, 0.66778094, 0.60751116, 0.394802, 0.88876283, 0.4992967, 0.913685, 0.5126276, 0.31567124, 0.15517022, 0.25738853, 0.95065016, 0.46436185, 0.23218602, 0.56505036, 0.7640109, 0.09191362, 0.06017749, 0.7948248, 0.13743167, 0.85851634, 0.578755, 0.28760704, 0.13184921, 0.55784, 0.59383327, 0.007337719, 0.46861604, 0.31112307, 0.08062537, 0.33833835, 0.015293708, 0.541975, 0.38214052, 0.8668698, 0.04065832, 0.43945628, 0.6610767, 0.44694275, 0.8487728, 0.7911693, 0.33415776, 0.14555527, 0.94175804, 0.43849084, 0.095858894, 0.22025794, 0.017959885, 0.78627133, 0.47368947, 0.053528015, 0.20038854, 0.07337133, 0.85522085, 0.9193087, 0.5146324, 0.39938548, 0.971611, 0.5871407, 0.1543597, 0.97602874, 0.06225404, 0.18737279, 0.33718324, 0.9549692, 0.038920015, 0.34139353, 0.9358679, 0.27331984, 0.9024317, 0.86224216, 0.7153058, 0.27769488, 0.824241, 0.25238916, 0.4948793, 0.12975529, 0.77602154, 0.50668365, 0.21300463, 0.884778, 0.18738495, 0.53389746, 0.1687875, 0.35214692, 0.5653193, 0.69561136, 0.05864211, 0.14492245, 0.8521376, 0.83646953, 0.416119, 0.15992665, 0.8182712, 0.40011352, 0.37019515, 0.8518576, 0.7149849, 0.9115014, 0.13328524, 0.7046979, 0.2371984, 0.111214116, 0.9120716, 0.9208662, 0.06360317, 0.5202445, 0.09866904, 0.14659214, 0.2629275, 0.89120066, 0.797822, 0.4339805, 0.19397406, 0.28549558, 0.21864726, 0.3575796, 0.4124478, 0.8468499, 0.08198859, 0.35118526, 0.49748322, 0.053980116, 0.30704916, 0.30298716, 0.39918154, 0.2816881, 0.74385446, 0.6590163, 0.6237566, 0.4114778, 0.3392905, 0.31122613, 0.67890936, 0.01342537, 0.02786821, 0.58878434, 0.6889002, 0.36484063, 0.6697477, 0.8660339, 0.83738923, 0.80138576, 0.21699402, 0.4780828, 0.33768442, 0.025448985, 0.43647078, 0.76335746, 0.37327543, 0.034529995, 0.6016785, 0.11657885, 0.28115, 0.37670454, 0.69592243, 0.29074693, 0.8334282, 0.89029354, 0.67256624, 0.6596837, 0.10104519, 0.72474205, 0.58064854, 0.44235742, 0.36908746, 0.18703483, 0.7302669, 0.8578351, 0.25104535, 0.42648348, 0.97678846, 0.5581102, 0.028629635, 0.723959, 0.3547385, 0.13951658, 0.30376077, 0.742309, 0.82682157, 0.37260672, 0.2780426, 0.8466213, 0.37635037, 0.4592084, 0.3485733, 0.71841913, 0.07293139, 0.29380447, 0.48921517, 0.72548944, 0.41292995, 0.0585436, 0.6998028, 0.49487817, 0.12114853, 0.5117317, 0.3636894, 0.45633256, 0.653457, 0.36406147, 0.44440264, 0.2219462, 0.5306148, 0.05853518, 0.46190208, 0.68171656, 0.04764763]"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at java.base/java.lang.Double.valueOf(Double.java:755)
	at io.nosqlbench.virtdata.core.composers.ComposerForLongFunction.lambda$andThen$48(ComposerForLongFunction.java:277)
	at io.nosqlbench.virtdata.core.bindings.DataMapper.apply(DataMapper.java:26)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.apply(StringCompositor.java:81)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:66)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:73)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:142)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:123)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:113)
	at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:353)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:99)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:38)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:46)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:77)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:120)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:109)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:130)
	at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.run(PolyglotScenarioController.java:57)
	at <js>.:program(<eval>:18)
	at org.graalvm.polyglot.Context.eval(Context.java:399)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:478)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:420)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.executeScenarioScripts(Scenario.java:304)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.runScenario(Scenario.java:263)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:392)
	at io.nosqlbench.engine.core.lifecycle.scenario.Scenario.call(Scenario.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NumberFormatException: For input string: "[0.41664743, 0.0041140798, 0.031210342, 0.3577026, 0.7661032, 0.46911007, 0.54842097, 0.26967052, 0.58288395, 0.22645862, 0.5034224, 0.9049926, 0.23829463, 0.32980722, 0.6761961, 0.6981883, 0.3200009, 0.4490906, 0.12666588, 0.6430993, 0.49963868, 0.31284282, 0.763792, 0.11513454, 0.67092836, 0.93725747, 0.54872674, 0.097864285, 0.7646463, 0.9818316, 0.67528826, 0.679239, 0.2656406, 0.14121564, 0.3102456, 0.6077616, 0.7327927, 0.48506156, 0.18762742, 0.25338155, 0.58579046, 0.063707665, 0.58357996, 0.60465467, 0.04848841, 0.044691086, 0.14575632, 0.041651297, 0.18028255, 0.92257524, 0.44763422, 0.65803826, 0.12804899, 0.70822024, 0.90674514, 0.65545326, 0.11204895, 0.11499816, 0.44230947, 0.5864353, 0.96790296, 0.58148766, 0.93778527, 0.80270666, 0.2831041, 0.10937845, 0.8053076, 0.28792813, 0.50862604, 0.40342772, 0.5568974, 0.02963415, 0.40321782, 0.029187795, 0.4384079, 0.74030435, 0.39401352, 0.993826, 0.039260495, 0.16641535, 0.8459175, 0.015068607, 0.19718032, 0.51955557, 0.27065313, 0.16150884, 0.7809726, 0.51703984, 0.39348963, 0.7283518, 0.6071092, 0.48824468, 0.68459404, 0.24343185, 0.34980676, 0.492753, 0.45056581, 0.28344908, 0.61025333, 0.34652892, 0.017417664, 0.1817564, 0.9689303, 0.6006299, 0.90755016, 0.4539173, 0.40951812, 0.53548676, 0.4688812, 0.76815206, 0.659321, 0.6644502, 0.13146335, 0.6750844, 0.3372118, 0.32972416, 0.6660541, 0.46084377, 0.2129152, 0.7485146, 0.45528877, 0.47468567, 0.31259716, 0.92716926, 0.8958603, 0.28182846, 0.27148324, 0.12159255, 0.75116074, 0.59003747, 0.07221658, 0.9897092, 0.9821176, 0.6505591, 0.57315195, 0.9013027, 0.78542703, 0.5950717, 0.4211729, 0.52863276, 0.7565085, 0.13213058, 0.28531376, 0.22839609, 0.8983835, 0.39091632, 0.71623194, 0.47023162, 0.3615875, 0.2184856, 0.8175504, 0.12303334, 0.27900133, 0.5292291, 0.566849, 0.45339718, 0.08979274, 0.47564128, 0.522547, 0.02864396, 0.5246605, 0.4956322, 0.53097874, 0.25780547, 0.87070465, 0.053854413, 0.30447194, 0.28424934, 0.29209283, 0.8257855, 0.84918666, 0.018738225, 0.30064487, 0.50120825, 0.7836194, 0.48977852, 0.070484295, 0.2786937, 0.7484871, 0.27036792, 0.8279852, 0.7355909, 0.7820941, 0.42583066, 0.80037546, 0.5605368, 0.66835177, 0.33273193, 0.5447857, 0.6558605, 0.6073436, 0.019365942, 0.075855136, 0.45607352, 0.90365696, 0.24260315, 0.6989602, 0.10360575, 0.9031459, 0.7602013, 0.53921854, 0.24418008, 0.9534409, 0.2077292, 0.65588814, 0.544023, 0.011964745, 0.9512949, 0.98649293, 0.7634876, 0.88554984, 0.83256096, 0.44663233, 0.4276707, 0.948232, 0.86184484, 0.18994078, 0.82322, 0.32606173, 0.507698, 0.91296905, 0.640866, 0.40231508, 0.11987478, 0.31411326, 0.86857235, 0.49456894, 0.98898596, 0.48263043, 0.14988042, 0.61491305, 0.33881086, 0.71110433, 0.19185369, 0.98263174, 0.38141716, 0.5309092, 0.56624264, 0.09057603, 0.3373434, 0.22150072, 0.13043882, 0.7747343, 0.75274223, 0.14761584, 0.57620484, 0.42330045, 0.05905397, 0.9144481, 0.73432475, 0.150127, 0.34640664, 0.25937915, 0.97647244, 0.6144487, 0.32702738, 0.4311388, 0.6927873, 0.5464044, 0.55545604, 0.23719904, 0.6912818, 0.6959132, 0.47528782, 0.6001572, 0.6639971, 0.68031275, 0.7648861, 0.57166755, 0.17419398, 0.24202004, 0.91730857, 0.13876812, 0.43690306, 0.5359196, 0.2950771, 0.2817587, 0.55254596, 0.49494272, 0.5608494, 0.7755488, 0.5624231, 0.06292067, 0.8160285, 0.968782, 0.72521937, 0.37803528, 0.93579715, 0.3072157, 0.81407696, 0.18710555, 0.63321847, 0.98953533, 0.43497646, 0.99093974, 0.11155998, 0.13598569, 0.7197043, 0.70945567, 0.9494274, 0.94431424, 0.11880333, 0.43696752, 0.36046597, 0.3510791, 0.4277881, 0.7343808, 0.17351837, 0.2470645, 0.02920208, 0.7804269, 0.940166, 0.39287722, 0.9119309, 0.8727847, 0.1009619, 0.8907118, 0.1870652, 0.37678367, 0.37059155, 0.98690844, 0.48942158, 0.10111245, 0.5524151, 0.96801627, 0.25896445, 0.8310115, 0.03947638, 0.2481636, 0.5569855, 0.33525857, 0.7332102, 0.07834539, 0.66778094, 0.60751116, 0.394802, 0.88876283, 0.4992967, 0.913685, 0.5126276, 0.31567124, 0.15517022, 0.25738853, 0.95065016, 0.46436185, 0.23218602, 0.56505036, 0.7640109, 0.09191362, 0.06017749, 0.7948248, 0.13743167, 0.85851634, 0.578755, 0.28760704, 0.13184921, 0.55784, 0.59383327, 0.007337719, 0.46861604, 0.31112307, 0.08062537, 0.33833835, 0.015293708, 0.541975, 0.38214052, 0.8668698, 0.04065832, 0.43945628, 0.6610767, 0.44694275, 0.8487728, 0.7911693, 0.33415776, 0.14555527, 0.94175804, 0.43849084, 0.095858894, 0.22025794, 0.017959885, 0.78627133, 0.47368947, 0.053528015, 0.20038854, 0.07337133, 0.85522085, 0.9193087, 0.5146324, 0.39938548, 0.971611, 0.5871407, 0.1543597, 0.97602874, 0.06225404, 0.18737279, 0.33718324, 0.9549692, 0.038920015, 0.34139353, 0.9358679, 0.27331984, 0.9024317, 0.86224216, 0.7153058, 0.27769488, 0.824241, 0.25238916, 0.4948793, 0.12975529, 0.77602154, 0.50668365, 0.21300463, 0.884778, 0.18738495, 0.53389746, 0.1687875, 0.35214692, 0.5653193, 0.69561136, 0.05864211, 0.14492245, 0.8521376, 0.83646953, 0.416119, 0.15992665, 0.8182712, 0.40011352, 0.37019515, 0.8518576, 0.7149849, 0.9115014, 0.13328524, 0.7046979, 0.2371984, 0.111214116, 0.9120716, 0.9208662, 0.06360317, 0.5202445, 0.09866904, 0.14659214, 0.2629275, 0.89120066, 0.797822, 0.4339805, 0.19397406, 0.28549558, 0.21864726, 0.3575796, 0.4124478, 0.8468499, 0.08198859, 0.35118526, 0.49748322, 0.053980116, 0.30704916, 0.30298716, 0.39918154, 0.2816881, 0.74385446, 0.6590163, 0.6237566, 0.4114778, 0.3392905, 0.31122613, 0.67890936, 0.01342537, 0.02786821, 0.58878434, 0.6889002, 0.36484063, 0.6697477, 0.8660339, 0.83738923, 0.80138576, 0.21699402, 0.4780828, 0.33768442, 0.025448985, 0.43647078, 0.76335746, 0.37327543, 0.034529995, 0.6016785, 0.11657885, 0.28115, 0.37670454, 0.69592243, 0.29074693, 0.8334282, 0.89029354, 0.67256624, 0.6596837, 0.10104519, 0.72474205, 0.58064854, 0.44235742, 0.36908746, 0.18703483, 0.7302669, 0.8578351, 0.25104535, 0.42648348, 0.97678846, 0.5581102, 0.028629635, 0.723959, 0.3547385, 0.13951658, 0.30376077, 0.742309, 0.82682157, 0.37260672, 0.2780426, 0.8466213, 0.37635037, 0.4592084, 0.3485733, 0.71841913, 0.07293139, 0.29380447, 0.48921517, 0.72548944, 0.41292995, 0.0585436, 0.6998028, 0.49487817, 0.12114853, 0.5117317, 0.3636894, 0.45633256, 0.653457, 0.36406147, 0.44440264, 0.2219462, 0.5306148, 0.05853518, 0.46190208, 0.68171656, 0.04764763]"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at java.base/java.lang.Double.valueOf(Double.java:755)
	at io.nosqlbench.virtdata.core.composers.ComposerForLongFunction.lambda$andThen$48(ComposerForLongFunction.java:277)
	at io.nosqlbench.virtdata.core.bindings.DataMapper.apply(DataMapper.java:26)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.apply(StringCompositor.java:81)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:66)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:73)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:142)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:123)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:113)
	at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:353)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:99)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:38)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:46)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.doStartActivity(ScenarioController.java:77)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:120)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:109)
	at io.nosqlbench.engine.core.lifecycle.scenario.ScenarioController.run(ScenarioController.java:130)
	at io.nosqlbench.engine.core.lifecycle.scenario.script.bindings.PolyglotScenarioController.run(PolyglotScenarioController.java:57)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:350)
	at com.oracle.truffle.host.GuestToHostCodeCache$1.executeImpl(GuestToHostCodeCache.java:96)
	at com.oracle.truffle.host.GuestToHostRootNode.execute(GuestToHostRootNode.java:80)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:177)
	at com.oracle.truffle.host.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:102)
	at com.oracle.truffle.host.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:386)
	at com.oracle.truffle.host.HostExecuteNode.doInvoke(HostExecuteNode.java:871)
	at com.oracle.truffle.host.HostExecuteNode.doOverloadedCached(HostExecuteNode.java:288)
	at com.oracle.truffle.host.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:241)
	at com.oracle.truffle.host.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:97)
	at com.oracle.truffle.host.HostObject.invokeMember(HostObject.java:454)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:2696)
	at com.oracle.truffle.host.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:2678)
	at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1534)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:306)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:251)
	at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:740)
	at com.oracle.truffle.js.nodes.JavaScriptNode.executeVoid(JavaScriptNode.java:192)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:80)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:55)
	at com.oracle.truffle.api.impl.DefaultBlockNode.executeGeneric(DefaultBlockNode.java:63)
	at com.oracle.truffle.js.nodes.control.AbstractBlockNode.execute(AbstractBlockNode.java:75)
	at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:149)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:88)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
	at com.oracle.truffle.js.lang.JavaScriptLanguage$ParsedProgramRoot.execute(JavaScriptLanguage.java:245)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1470)
	at com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	... 12 more
    7651 WARN  [scenarios:001] CoreMotor    attempted to stop motor 0: from non Running state:Finished
    ```
</details>

#### Other Bindings Tried

With a binding like below,
```
frozen<list<float>>: ListSizedHashed(HashRange(1,1000),ListHashed(HashRange(0.0,1.0),DoubleToFloat()))
```

I got,
```
Caused by: io.nosqlbench.api.errors.BasicError: adapter method is not implemented on class io.nosqlbench.virtdata.api.bindings.NBFunctionConverter:
    // Ignore the place holders in your implementation, but ensure the return type is accurate
    public static LongFunction<Object> adapt(DoubleFunction<Float> f, Float i1, LongFunction i2, Object i3) {
    }

	at io.nosqlbench.virtdata.api.bindings.VirtDataConversions.adaptFunction(VirtDataConversions.java:145)
	at io.nosqlbench.virtdata.api.bindings.VirtDataConversions.adaptFunctionList(VirtDataConversions.java:76)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.ListHashed.<init>(ListHashed.java:55)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments(MethodHandleImpl.java:538)
	at io.nosqlbench.virtdata.core.bindings.VirtDataFunctionResolver.resolveFunctions(VirtDataFunctionResolver.java:118)
	... 73 more
```

**What was Expected**
Bindings created and ingested into the CQL table properly.

**Additional context**
OS: `Linux (distribution)`
environment: `Ubuntu 22.04.3 LTS`
version info:
```
$ ./nb5 --version
5.17.9-release
```

**Screenshots, if applicable**

**Comment by msmygit** [comment]
User error. It's a simple binding as below,
```
ListSizedHashed(HashRange(3,5)->int,HashRange(0.0f,1.0f))
```

**Comment by jshook** [comment]
I fixed the wrong example, added one to illustrate the above, and checked the other list functions for incorrect examples as well.

For future reference, you can also do `nb5 virtdata testmapper 'ListSizedStepped(2,HashRange(1f,10f))' -p` for testing these things quickly.
