### ISSUE TITLE
nb returns error when running with --docker-metrics

### ISSUE THREAD

**Issue by joechu1** [nosqlbench/nosqlbench#186]
I get an exception when running a benchmark with the flag --docker-metrics. Attempting to run the same command again will start the benchmark and Grafana, but the NoSqlBench dashboard graphs don't seem to be populated. Prometheus appears to be working for the second attempt.

```
./nb cql-iot cyclerate=100 --progress console:15s --docker-metrics

22:12:51.392 [main] WARN  i.n.engine.docker.RestHelper - Unable to configure dashboard, grafana precondition failed (status 412): {"message":"The dashboard has been changed by someone else","status":"version-mismatch"}
22:12:51.401 [main] ERROR i.n.engine.core.ScenarioErrorHandler - internal error: io.nosqlbench.nb.api.errors.BasicError: When trying to configure grafana, any errors indicate that you may be trying to RE-configure an instance. This may be a bug. If you already have a docker stack running, you can just use '--report-graphite-to localhost:9109'
 instead of --docker-metrics.
java.lang.RuntimeException: io.nosqlbench.nb.api.errors.BasicError: When trying to configure grafana, any errors indicate that you may be trying to RE-configure an instance. This may be a bug. If you already have a docker stack running, you can just use '--report-graphite-to localhost:9109'
 instead of --docker-metrics.
	at io.nosqlbench.engine.docker.RestHelper.post(RestHelper.java:80)
	at io.nosqlbench.engine.docker.DockerMetricsManager.configureGrafana(DockerMetricsManager.java:315)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startGrafana(DockerMetricsManager.java:93)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startMetrics(DockerMetricsManager.java:50)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:196)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:53)
Caused by: io.nosqlbench.nb.api.errors.BasicError: When trying to configure grafana, any errors indicate that you may be trying to RE-configure an instance. This may be a bug. If you already have a docker stack running, you can just use '--report-graphite-to localhost:9109'
 instead of --docker-metrics.
	at io.nosqlbench.engine.docker.RestHelper.post(RestHelper.java:66)
	... 5 common frames omitted
io.nosqlbench.nb.api.errors.BasicError: When trying to configure grafana, any errors indicate that you may be trying to RE-configure an instance. This may be a bug. If you already have a docker stack running, you can just use '--report-graphite-to localhost:9109'
 instead of --docker-metrics.

./nb cql-iot cyclerate=100 --progress console:15s --docker-metrics
22:14:02.585 [main] WARN  io.nosqlbench.engine.cli.NBCLI - Docker Containers are started, for grafana and prometheus, hit these urls in your browser: http://<host>:3000 and http://<host>:9090
Logging to logs/scenario_20200728_221402_623.log
cqliot_default_rampup: 0.01%/Running (details: min=0 cycle=960 max=10000000)
cqliot_default_schema: 100.00%/Finished (details: min=0 cycle=3 max=3) (last report)
cqliot_default_rampup: 0.02%/Running (details: min=0 cycle=2460 max=10000000)
cqliot_default_rampup: 0.04%/Running (details: min=0 cycle=3960 max=10000000)
cqliot_default_rampup: 0.05%/Running (details: min=0 cycle=5460 max=10000000)
cqliot_default_rampup: 0.06%/Running (details: min=0 cycle=6111 max=10000000)
cqliot_default_rampup: 0.07%/Running (details: min=0 cycle=6659 max=10000000)
cqliot_default_rampup: 0.07%/Running (details: min=0 cycle=7175 max=10000000)
cqliot_default_rampup: 0.08%/Running (details: min=0 cycle=7762 max=10000000)
cqliot_default_rampup: 0.08%/Running (details: min=0 cycle=8269 max=10000000)
...
```

![image](https://user-images.githubusercontent.com/5282594/88727962-870bb100-d0e5-11ea-9704-47a5079d8566.png)

This is with latest version of nosqlbench (3.12.134 at the time of writing). I haven't tested them all, but it was still working at least up to version 3.12.126.

**Comment by phact** [comment]
Are you using an alias? What do you see in prometheus?

**Comment by joechu1** [comment]
This was done downloading the appimage binary `nb` file from Github, making it executable, and running the command above. I don't believe an alias is involved. This is run using the root user though, if that matters. For prometheus, it looks like it is collecting metrics:
![image](https://user-images.githubusercontent.com/5282594/89156845-4914ef80-d520-11ea-8bae-0183d7fe353c.png)
I'll also keep my test environment up, if anybody would like to connect and see what's going on.

**Comment by jshook** [comment]
Since this report, there have been many enhancements to docker handling for robustness and initial configuration. This should be fixed in the latest nb4 release candidate.
