### ISSUE TITLE
Prometheus version 2.4.3 is not available any more

### ISSUE THREAD

**Issue by yabinmeng** [nosqlbench/nosqlbench#189]
**Describe the bug**
When executing "nb" command with --docker-metrics, the following error is thrown up:

02:19:30.723 [main] ERROR i.n.engine.core.ScenarioErrorHandler - internal error: {"message":"No such image: prom/prometheus:v2.4.3"}

com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: prom/prometheus:v2.4.3"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:129)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
	at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
	at io.nosqlbench.engine.docker.DockerHelper.startDocker(DockerHelper.java:125)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startPrometheus(DockerMetricsManager.java:128)
	at io.nosqlbench.engine.docker.DockerMetricsManager.startMetrics(DockerMetricsManager.java:48)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:191)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:48)
{"message":"No such image: prom/prometheus:v2.4.3"}

**What was Expected**
Shoud we use version "latest" in order to avoid similar error in the future?

**Comment by XN137** [comment]
relevant code:
https://github.com/nosqlbench/nosqlbench/blob/86a92d9ab905f765eae74be9a1ba6a7d891537a1/engine-docker/src/main/java/io/nosqlbench/engine/docker/DockerMetricsManager.java#L97-L103

**Comment by jshook** [comment]
I'm updating the tag to 'latest', given the stable release train of prom so far. However, this needs to be also turned into an option. I'll close this when it is released, but I'll also add an issue to allow the version to be specified.

**Comment by jshook** [comment]
Tagging option issue added as #197

**Comment by jshook** [comment]
The previous fix for this isn't sufficient. The docker bootstrapping logic is not verifying that the prometheus image of the specified tag is present before starting the containers. It is only doing a cursory check. Thus, if it sees prom/prometheus available, it assumes that it is ok to go ahead and start the containers.

The full fix for this needs to ensure that the specified (or default) names and tags are used for each step of state checking and boostrapping when --docker-metrics is used.

**Comment by dave2wave** [comment]
We are not using Prometheus and the NB 5.21 efforts to replace "graphite mode" will involve a docker compose of grafana and victoria metrics.
