### ISSUE TITLE
Exception when running --list-workloads under openjdk14 under Windows 10 when using nb 3.12.138

### ISSUE THREAD

**Issue by mgent** [nosqlbench/nosqlbench#192]
**Describe the bug**
Running:
java -jar nb.jar --list-workloads
Produces:
18:40:37.687 [main] ERROR i.n.engine.core.ScenarioErrorHandler - internal error: Illegal char <*> at index 1: .*.yaml
java.nio.file.InvalidPathException: Illegal char <*> at index 1: .*.yaml
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at io.nosqlbench.nb.api.content.ResolverForFilesystem.resolvePath(ResolverForFilesystem.java:18)
        at io.nosqlbench.nb.api.content.ResolverForFilesystem.resolve(ResolverForFilesystem.java:29)
        at io.nosqlbench.nb.api.content.URIResolver.resolve(URIResolver.java:87)
        at io.nosqlbench.nb.api.content.URIResolver.resolve(URIResolver.java:72)
        at io.nosqlbench.nb.api.content.NBIO.list(NBIO.java:341)
        at io.nosqlbench.engine.api.scenarios.NBCLIScenarioParser.getWorkloadsWithScenarioScripts(NBCLIScenarioParser.java:265)
        at io.nosqlbench.engine.cli.NBCLIScenarios.printWorkloads(NBCLIScenarios.java:13)
        at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:102)
        at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:48)
Illegal char <*> at index 1: .*.yaml

**To Reproduce**
1. Install OpenJDK 14.0.2 under Windows 10
2. Download nb 3.12.138  (the latest at time of writing)
3. Run java -jar nb.jar --list-workloads

**What was Expected**
For nb to show its list of built-in scenarios.

**Additional context**
None

**Screenshots, if applicable**
n/a

**Comment by dave2wave** [comment]
We are on JDK21
