### ISSUE TITLE
Support both 'block' and 'blocks' as being accepted tag filter keys

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#2030]
**What is the ideal scenario for using this feature?**
Consider a workload yaml file as below,
```
scenarios:
  default:
    create_db_ddl: run driver=my_driver tags==blocks:schema_db cycles=1 <other params>

blocks:
  schema_db:
    ops:
      op1:
        create_database_ddl: TEMPLATE(database_id)
```
where I've `blocks` (plural) as opposed to the current expected singular `block` in the tag filter's key. With the latest release, this gives the following error:

<details>
<summary>🐛 🚨 There were no active op templates with tag filter 'blocks:schema_db', since all 1 were filtered out</summary>

```
ERROR [main] ERRORHANDLER There were no active op templates with tag filter 'blocks:schema_db', since all 1 were filtered out.
io.nosqlbench.nb.api.errors.BasicError: There were no active op templates with tag filter 'blocks:schema_db', since all 1 were filtered out.
	at io.nosqlbench.engine.api.activityimpl.SimpleActivity.loadOpTemplates(SimpleActivity.java:484)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:91)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:30)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:43)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.doStartActivity(ContainerActivitiesController.java:76)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:124)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:113)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:134)
	at io.nosqlbench.engine.core.lifecycle.commands.CMD_run.invoke(CMD_run.java:40)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBBaseCommand.apply(NBBaseCommand.java:53)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBInvokableCommand.invokeSafe(NBInvokableCommand.java:45)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.NBBufferedContainer.apply(NBBufferedContainer.java:137)
	at io.nosqlbench.engine.core.lifecycle.session.NBSession.apply(NBSession.java:96)
	at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:473)
	at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:124)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:104)
Scenario stopped due to error. See logs for details.

Process finished with exit code 2
```
</details>

**Is your feature request related to a problem? Please describe.**
It'd be nice to support both `block` (which works today) and `blocks` as accepted form of tag filter keys.

**Comment by msmygit** [comment]
It looks like the changes will be needed here - https://github.com/nosqlbench/nosqlbench/blob/main/nb-apis/adapters-api/src/main/java/io/nosqlbench/adapters/api/activityconfig/yaml/OpsDocList.java#L78-L83 is where it gets filtered, which gets into the https://github.com/nosqlbench/nosqlbench/blob/main/nb-apis/nb-api/src/main/java/io/nosqlbench/nb/api/tagging/TagFilter.java#L238

**Comment by dave2wave** [comment]
I think that this can be simply done in `OpDef.java` by adding to the `composeTags` method.

```
    private LinkedHashMap<String, String> composeTags() {
        LinkedHashMap<String, String> tagsWithName = new LinkedHashMap<>(new MultiMapLookup<>(rawOpDef.getTags(), block.getTags()));
        tagsWithName.put("block",block.getName());
        tagsWithName.put("blocks",block.getName());
        tagsWithName.put("name",this.rawOpDef.getName());
        tagsWithName.put("names",this.rawOpDef.getName());
        tagsWithName.put("op",this.rawOpDef.getName());
        tagsWithName.put("ops",this.rawOpDef.getName());
        return tagsWithName;
    }

**Comment by dave2wave** [comment]
I tried that approach but it runs into some complexity with SpecTests. We'll need to instead build in some type of stripper of "s" in `TagFilter`.

**Comment by dave2wave** [comment]
Generally improve error messaging. Don't pluralize unless its safe.
