### ISSUE TITLE
5.21.4-release errors on binding that works on 5.17.9-release with MapSized

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#2055]
**Describe the bug**

Consider a workload yaml,
```
$ cat map_sized.yaml 
bindings:
  map_sized: MapSized(1, NumberNameToString(), NumberNameToString(), ToString(), ToString())
  map<text,text>: MapSized(3, Combinations('A-Z;0-9'), NumberNameToString(), ToString());
```

NB version `5.17.9-release` produces,
```
$ ~/nb5 --version
5.17.9-release

$ ~/nb5 run workload=./map_sized.yaml driver=stdout tags=block:'rampup.*' cycles=10 format=readout --show-stacktraces

     map_sized : {zero=zero}
map<text,text> : {0.0=zero, A0=zero}

     map_sized : {one=one}
map<text,text> : {A1=one, 1.0=one}

     map_sized : {two=two}
map<text,text> : {2.0=two, A2=two}

     map_sized : {three=three}
map<text,text> : {3.0=three, A3=three}

     map_sized : {four=four}
map<text,text> : {4.0=four, A4=four}

     map_sized : {five=five}
map<text,text> : {A5=five, 5.0=five}

     map_sized : {six=six}
map<text,text> : {6.0=six, A6=six}

     map_sized : {seven=seven}
map<text,text> : {7.0=seven, A7=seven}

     map_sized : {eight=eight}
map<text,text> : {8.0=eight, A8=eight}

     map_sized : {nine=nine}
map<text,text> : {A9=nine, 9.0=nine}
```
whereas NB `5.21.4-release` errors:
```
$ java --enable-preview -jar nb5.jar --version
5.21.4-release


$ java --enable-preview -jar ./nb5.jar run workload=./map_sized.yaml driver=stdout tags=block:'rampup.*' cycles=10 format=readout --show-stacktraces
    1468 ERROR [main] NBINVOKE     error   [CMD_run {container="default",instance="default",jobname="nosqlbench",node="191.100.40.91",session="o0NpBmG",step="run"}]: (stack trace follows): CMD_run {container="default",instance="default",jobname="nosqlbench",node="191.100.40.91",session="o0NpBmG",step="run"}: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.nio.CharBuffer (java.lang.Long and java.nio.CharBuffer are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.nio.CharBuffer (java.lang.Long and java.nio.CharBuffer are in module java.base of loader 'bootstrap')
	at io.nosqlbench.virtdata.library.basics.shared.conversions.from_charbuffer.ToString.apply(ToString.java:29)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized.apply(MapSized.java:78)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized.apply(MapSized.java:42)
	at io.nosqlbench.virtdata.core.bindings.DataMapper.apply(DataMapper.java:26)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.apply(StringCompositor.java:84)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:66)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:75)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:142)
	at java.base/java.util.Map.forEach(Map.java:733)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:123)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:113)
	at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:381)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:149)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:30)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:43)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.doStartActivity(ContainerActivitiesController.java:76)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:124)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:113)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:134)
	at io.nosqlbench.engine.core.lifecycle.commands.CMD_run.invoke(CMD_run.java:40)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBBaseCommand.apply(NBBaseCommand.java:53)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBInvokableCommand.invokeSafe(NBInvokableCommand.java:45)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.NBBufferedContainer.apply(NBBufferedContainer.java:137)
	at io.nosqlbench.engine.core.lifecycle.session.NBSession.apply(NBSession.java:96)
	at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:493)
	at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:127)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:107)
    1472 ERROR [main] NBSession    While running in container 'default', command 'run workload=./map_sized.yaml driver=stdout tags='block:rampup.*' cycles=10 format=readout', an error occurred: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.nio.CharBuffer (java.lang.Long and java.nio.CharBuffer are in module java.base of loader 'bootstrap')
    1489 ERROR [main] ERRORHANDLER internal error: class java.lang.Long cannot be cast to class java.nio.CharBuffer (java.lang.Long and java.nio.CharBuffer are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.nio.CharBuffer (java.lang.Long and java.nio.CharBuffer are in module java.base of loader 'bootstrap')
	at io.nosqlbench.virtdata.library.basics.shared.conversions.from_charbuffer.ToString.apply(ToString.java:29)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized.apply(MapSized.java:78)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized.apply(MapSized.java:42)
	at io.nosqlbench.virtdata.core.bindings.DataMapper.apply(DataMapper.java:26)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.apply(StringCompositor.java:84)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:66)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:75)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:142)
	at java.base/java.util.Map.forEach(Map.java:733)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:123)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:113)
	at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:381)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:149)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:30)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:43)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.doStartActivity(ContainerActivitiesController.java:76)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:124)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:113)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:134)
	at io.nosqlbench.engine.core.lifecycle.commands.CMD_run.invoke(CMD_run.java:40)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBBaseCommand.apply(NBBaseCommand.java:53)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBInvokableCommand.invokeSafe(NBInvokableCommand.java:45)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.NBBufferedContainer.apply(NBBufferedContainer.java:137)
	at io.nosqlbench.engine.core.lifecycle.session.NBSession.apply(NBSession.java:96)
	at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:493)
	at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:127)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:107)
Scenario stopped due to error. See logs for details.
```

Java Version used:
```
$ java -version
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

**To Reproduce**
1. ...

**What was Expected**

**Additional context**
OS: Linux (distribution): 
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```
environment: n/a
version info (`./nb --version` or `java -jar nb.jar --version`): see above

**Screenshots, if applicable**
n/a

**Comment by dave2wave** [comment]
This looks like a bug with selecting the KeyFunc.

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.nio.CharBuffer (java.lang.Long and java.nio.CharBuffer are in module java.base of loader 'bootstrap')
	at io.nosqlbench.virtdata.library.basics.shared.conversions.from_charbuffer.ToString.apply(ToString.java:29)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized.apply(MapSized.java:78)
	at io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized.apply(MapSized.java:42)
	at io.nosqlbench.virtdata.core.bindings.DataMapper.apply(DataMapper.java:26)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.apply(StringCompositor.java:84)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:66)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:75)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49)
	at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:143)
	at java.base/java.util.Map.forEach(Map.java:733)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:124)
	at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:114)
	at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:379)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:150)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:30)
	at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:43)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.doStartActivity(ContainerActivitiesController.java:76)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:124)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:113)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:134)
	at io.nosqlbench.engine.core.lifecycle.commands.CMD_run.invoke(CMD_run.java:40)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBBaseCommand.apply(NBBaseCommand.java:53)
	at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBInvokableCommand.invokeSafe(NBInvokableCommand.java:45)
	at io.nosqlbench.engine.core.lifecycle.scenario.container.NBBufferedContainer.apply(NBBufferedContainer.java:137)
	at io.nosqlbench.engine.core.lifecycle.session.NBSession.apply(NBSession.java:141)
	at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:465)
	at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:129)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:109)
```

**Comment by dave2wave** [comment]
I validated that the issue is with `ToString()` in the bindings

**Comment by dave2wave** [comment]
Trace gives that there are resolution errors for LongFunction -> ToString conversions:
```
    1233 TRACE [main] DataMapperLibrary BY-SINGLE-PREFERRED-TYPE removing func long->io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized->java.util.Map [Integer=>Integer,Combinations=>Combinations,NumberNameToString=>NumberNameToString,ToString=>ToString] because long->io.nosqlbench.virtdata.library.basics.shared.from_long.to_collection.MapSized->java.util.Map [Integer=>Integer,Combinations=>Combinations,NumberNameToString=>NumberNameToString,ToString=>ToString] has more preferred types.
 ```

**Comment by dave2wave** [comment]
If I change the `ToString()` to `ToLong()` then the results are the expected results.

There is some type of bug here, but it's not clear if it is a user bug or there is a problem with resolving `ToString` functions correctly.

**Comment by dave2wave** [comment]
@jshook There is some type of trouble with binding function resolution which is beyond my current understanding of the codebase.

**Comment by dave2wave** [comment]
@jshook Since you are in the binding functions, I think that there is a data type mapping problem hiding here ...

**Comment by dave2wave** [comment]
@jshook #2133 did not fix this bug.

**Comment by jshook** [comment]
The issue is caused by the third value binding function `ToString()` being selected as `io.nosqlbench.virtdata.library.basics.shared.conversions.from_charbuffer.ToString`, which was added after 5.17.9-release and before 5.21.4. The function resolver simply does not now how to select the correct version, but defaulting to a non-scalar type on input is certainly not preferred. A possible fix here for the short term might be to prioritize numeric types over other types when there is a tie. A longer-term fix means exposing the receiving prototype slot to the resolver for candidate function prototypes.
