### ISSUE TITLE
Failed to read large HDF5 file that are created using chunked storage

### ISSUE THREAD

**Issue by yabinmeng** [nosqlbench/nosqlbench#2105]
**Describe the bug**
I have converted Cohere Wikipedia (English) dataset into a HDF5 file that contains 2 groups:
- `query` group has the first 10K rows 
- `base` group has the rest of rows (roughly 41.5M rows)

Because the `base` group is very large beyond the physical memory, I generate the `base` group in the HDF5 file using its chunked storage mechanism. Basically, for the total 41.5 M rows in the `base` group, every 1M rows are written to the HDF5 file and then expand the HDF5 storage size to another 1M rows. 

The result HDF5 file is 159GB in size
```
$ ls -ltrh largerealvec/cohere_wiki_en.hdf5
-rw-r--r-- 1 yabinmeng yabinmeng 159G Dec  7 21:18 largerealvec/cohere_wiki_en.hdf5
```

There are no issues when using Python CLI interpreter to read this file
```
>>> import h5py
>>> f = h5py.File('./cohere_wiki_en.hdf5', 'r')
>>> print(f['base'].shape)
(41478110, 1024)
>>> print(f['base'][-1])
[ 0.00431824  0.00419617 -0.02626038 ...  0.00047946 -0.01599121
 -0.00356865]
>>> print(f['base'][-1].shape)
(1024,)
```

I constructed a simple NB yaml file to test the bindings to read from this HDF5 file
```
bindings:
  query_vector: HdfFileToFloatList("file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5", "/query"); ToCqlVector();
  base_vector: HdfFileToFloatList("file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5", "/base"); ToCqlVector();
```  

I confirm that reading from `query` group is working fine because it is constructed using HDF5's default (continuous) approach; but when reading from `base` group, it failed with the following error stack:
```
2024-12-08 00:12:00,371 [main] INFO : Opened HDF5 file '/home/yabinmeng/largerealvec/cohere_wiki_en.hdf5'
2024-12-08 00:12:00,371 [main] INFO : Lazy loading children of '//'
2024-12-08 00:12:00,371 [main] INFO : Lazy loading children of '//'
2024-12-08 00:12:00,786 [main] ERROR: Error while composing functions:

2024-12-08 00:12:00,786 [main] ERROR: composer: class:ComposerForLongFunction, toString:io.nosqlbench.virtdata.core.composers.ComposerForLongFunction@773e2eb5
2024-12-08 00:12:00,787 [main] ERROR: outer: class:class io.nosqlbench.datamappers.functions.to_cqlvector.from_number_list.ToCqlVector, toString:io.nosqlbench.datamappers.functions.to_cqlvector.from_number_list.ToCqlVector@d8948cd
2024-12-08 00:12:00,788 [main] ERROR: error   [CMD_run {container="default",instance="default",jobname="nosqlbench",node="10.128.0.26",session="odyBYg9",step="run"}]: (stack trace follows): CMD_run {container="default",instance="default",jobname="nosqlbench",node="10.128.0.26",session="odyBYg9",step="run"}: java.lang.RuntimeException: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
2024-12-08 00:12:00,791 [main] INFO : VARS:{}
2024-12-08 00:12:00,794 [main] ERROR: While running in container 'default', command 'run driver=stdout workload=test.yaml cycles=1', an error occurred: java.lang.RuntimeException: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
2024-12-08 00:12:00,803 [main] INFO : ExecutionResult{status=ERROR, startedAt=1733616719867, endedAt=1733616720794, total=0.93S, exception=java.lang.RuntimeException: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading, iolog='ERROR:java.lang.RuntimeException: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading'}
2024-12-08 00:12:00,818 [main] ERROR: Error from driver or included library: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
java.lang.RuntimeException: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
        at io.nosqlbench.virtdata.core.bindings.ResolverDiagnostics.getResolvedFunctionOrThrow(ResolverDiagnostics.java:48) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.bindings.ResolverDiagnostics.getResolvedFunction(ResolverDiagnostics.java:43) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveFunctionFlow(VirtDataComposer.java:223) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.bindings.VirtData.getOptionalMapper(VirtData.java:107) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.templates.StringCompositor.lambda$new$1(StringCompositor.java:52) ~[nb5.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:51) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.templates.StringCompositor.<init>(StringCompositor.java:75) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:49) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.templates.StringBindings.<init>(StringBindings.java:45) ~[nb5.jar:?]
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.lambda$applyTemplateFields$1(ParsedTemplateMap.java:142) ~[nb5.jar:?]
        at java.base/java.util.Map.forEach(Map.java:733) ~[?:?]
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.applyTemplateFields(ParsedTemplateMap.java:123) ~[nb5.jar:?]
        at io.nosqlbench.engine.api.templating.ParsedTemplateMap.<init>(ParsedTemplateMap.java:113) ~[nb5.jar:?]
        at io.nosqlbench.adapters.api.templating.ParsedOp.<init>(ParsedOp.java:381) ~[nb5.jar:?]
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivity.<init>(StandardActivity.java:149) ~[nb5.jar:?]
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:62) ~[nb5.jar:?]
        at io.nosqlbench.engine.api.activityimpl.uniform.StandardActivityType.getActivity(StandardActivityType.java:30) ~[nb5.jar:?]
        at io.nosqlbench.engine.api.activityapi.core.ActivityType.getAssembledActivity(ActivityType.java:64) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.activity.ActivityLoader.loadActivity(ActivityLoader.java:43) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.doStartActivity(ContainerActivitiesController.java:76) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:124) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:113) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.container.ContainerActivitiesController.run(ContainerActivitiesController.java:134) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.commands.CMD_run.invoke(CMD_run.java:40) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBBaseCommand.apply(NBBaseCommand.java:53) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.execution.NBInvokableCommand.invokeSafe(NBInvokableCommand.java:45) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.scenario.container.NBBufferedContainer.apply(NBBufferedContainer.java:137) ~[nb5.jar:?]
        at io.nosqlbench.engine.core.lifecycle.session.NBSession.apply(NBSession.java:96) ~[nb5.jar:?]
        at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:493) ~[nb5.jar:?]
        at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:127) [nb5.jar:?]
        at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:107) [nb5.jar:?]
Caused by: java.lang.RuntimeException: FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
        at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveDiagnosticFunctionFlow(VirtDataComposer.java:213) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveFunctionFlow(VirtDataComposer.java:222) ~[nb5.jar:?]
        ... 29 more
Caused by: io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
        at io.jhdf.dataset.chunked.ChunkedDatasetBase.getSliceDataBuffer(ChunkedDatasetBase.java:316) ~[nb5.jar:?]
        at io.jhdf.dataset.DatasetBase.getData(DatasetBase.java:172) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.library.hdf5.from_long.AbstractHdfFileToVectorType.getDataFrom(AbstractHdfFileToVectorType.java:43) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.library.hdf5.from_long.to_list.HdfFileToFloatList.apply(HdfFileToFloatList.java:52) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.library.hdf5.from_long.to_list.HdfFileToFloatList.apply(HdfFileToFloatList.java:41) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.composers.ComposerForLongFunction.andThen(ComposerForLongFunction.java:43) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.composers.FunctionAssembly.andThen(FunctionAssembly.java:42) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveDiagnosticFunctionFlow(VirtDataComposer.java:207) ~[nb5.jar:?]
        at io.nosqlbench.virtdata.core.bindings.VirtDataComposer.resolveFunctionFlow(VirtDataComposer.java:222) ~[nb5.jar:?]
        ... 29 more
2024-12-08 00:12:00,829 [main] ERROR: cause (see stack trace for details):FUNCTION resolution failed: 'HdfFileToFloatList('file:///home/yabinmeng/largerealvec/cohere_wiki_en.hdf5','/base'); ToCqlVector()': io.jhdf.exceptions.UnsupportedHdfException: Chunked datasets don't support slice reading
```

**Comment by yabinmeng** [comment]
NB works fine with a HDF5 file with the default, flat structure.
