### ISSUE TITLE
Prepared: true statement params yields Caused by: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#222]
**Describe the bug**
`Prepared: true` yields the following exception,

```
Logging to logs/scenario_20201012_124111_205.log
12:41:12.122 [scenarios:001] WARN  i.n.a.c.s.core.CQLSessionCache - The speculative behavior is changing:
If the cql speculative parameter is not provided, it uses a default speculative
policy, as in speculative=default, rather than leaving speculative off.
If you want to keep this behavior or silence this warning, add one of
speculative=none OR speculative=default to your activity params.
This release, the default is speculative=default if the parameter is not specified.
After 10/01/2020, the default will be speculative=none if the parameter is not specified.
Note: speculative=default is the same as speculative=p99.0:5:15000
which is considered aggressive for some systems. This warning will go away after 10/01/2020.

12:41:14.083 [scenarios:001] WARN  c.d.d.c.p.DCAwareRoundRobinPolicy - Some contact points don't match local data center. Local DC = oltp. Non-conforming contact points: /10.101.32.96:9042 (olasgp)
12:41:15.221 [read-by-map-values:004] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Freda](String)
java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Freda](String)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:41)
	at io.nosqlbench.activitytype.cql.statements.core.ReadyCQLStatement.bind(ReadyCQLStatement.java:47)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:92)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:73)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:49)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:12)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:39)
	... 7 common frames omitted
12:41:16.139 [read-by-map-values:002] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Violet](String)
java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Violet](String)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:41)
	at io.nosqlbench.activitytype.cql.statements.core.ReadyCQLStatement.bind(ReadyCQLStatement.java:47)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:92)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:73)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:49)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:12)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:39)
	... 7 common frames omitted
12:41:17.135 [read-by-map-values:001] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Norman](String)
java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Norman](String)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:41)
	at io.nosqlbench.activitytype.cql.statements.core.ReadyCQLStatement.bind(ReadyCQLStatement.java:47)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:92)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:73)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:49)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:12)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:39)
	... 7 common frames omitted
12:41:18.133 [read-by-map-values:003] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[John](String)
java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[John](String)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:41)
	at io.nosqlbench.activitytype.cql.statements.core.ReadyCQLStatement.bind(ReadyCQLStatement.java:47)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:92)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:73)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:49)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:12)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:39)
	... 7 common frames omitted
12:41:19.129 [read-by-map-values:005] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Lisa](String)
java.lang.RuntimeException: Binding error:BindingsTemplate:'first_name'=>"Template('{}', FirstNames())"=>[Lisa](String)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:41)
	at io.nosqlbench.activitytype.cql.statements.core.ReadyCQLStatement.bind(ReadyCQLStatement.java:47)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runPhase(CqlAction.java:92)
	at io.nosqlbench.activitytype.cql.core.CqlAction.runCycle(CqlAction.java:73)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:49)
	at io.nosqlbench.activitytype.cql.statements.binders.UnsettableValuesBinder.bindValues(UnsettableValuesBinder.java:12)
	at io.nosqlbench.virtdata.core.bindings.ContextualArrayBindings.bind(ContextualArrayBindings.java:39)
	... 7 common frames omitted
12:41:19.137 [scenarios:001] WARN  i.n.engine.core.script.Scenario - Error in scenario, shutting down.
12:41:19.646 [main] ERROR i.n.engine.core.ScenarioErrorHandler - Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:152)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:117)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:75)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:322)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:53)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004
	at io.nosqlbench.engine.core.script.Scenario.run(Scenario.java:268)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:296)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:381)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:343)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
	at io.nosqlbench.engine.core.script.Scenario.run(Scenario.java:249)
	... 6 common frames omitted
Caused by: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004
	at io.nosqlbench.engine.core.ActivityExecutor.notifyException(ActivityExecutor.java:475)
	at io.nosqlbench.engine.core.ActivityExceptionHandler.uncaughtException(ActivityExceptionHandler.java:30)
	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1993)
java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error in activity thread read-by-map-values:004
```

**To Reproduce**
Download the latest version `nb.jar`,
```
$ java -jar nb.jar --version
3.12.153
```

### Bindings File
```
$ cat rococo.yaml 
bindings:
 first_name: Template('{}', FirstNames())
blocks:
  - tags:
      phase: schema
      type: read-by-map-values
    params:
      prepared: true
    statements:
     - create-keyspace: |
         SELECT * FROM <<keyspace:secret_keyspace>>.<<table:secret_table>> WHERE c2 CONTAINS '{first_name}' <<query_suffix:LIMIT 10>>;
       tags:
         name: main-read-by-map-values
```
Create a table and SAI like as follows:
```
cassandra@cqlsh:test2> select * from rococo where c2 contains 'Norman';
 pk1 | c1     | c2
-----+--------+------------
   1 | Norman | ['Norman']
(1 rows)
cassandra@cqlsh:test2> desc rococo;
CREATE TABLE test2.rococo (
    pk1 int PRIMARY KEY,
    c1 text,
    c2 list<text>
) WITH additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND nodesync = {'enabled': 'true', 'incremental': 'true'}
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX test2_rococo_c1_sai_idx ON test2.rococo (c1) USING 'StorageAttachedIndex' WITH OPTIONS = {'normalize': 'true', 'case_sensitive': 'true'};
CREATE CUSTOM INDEX test2_rococo_c2_sai_idx ON test2.rococo (values(c2)) USING 'StorageAttachedIndex' WITH OPTIONS = {'normalize': 'true', 'case_sensitive': 'true'};
```
Fun the NB with the following:
```
$ java -jar nb.jar run driver=cql workload=rococo.yaml tags=phase:schema cycles=5 cyclerate=1 threads=auto alias=read-by-map-values --show-stacktraces keyspace=test2 table=rococo host=<IP_LIST> username=cassandra password=cassandra
```
**What was Expected**
I expect this to work just like how it would behave when I've `prepared: false`. Understood that `prepared: true` cannot be done for schema DDL operations.

**Additional context**
OS: macOS ...
environment: regular openstack nebula cluster
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             16
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz
Stepping:              4
CPU MHz:               2095.078
BogoMIPS:              4190.15
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 arat pku md_clear
```
version info (`./nb --version` or `java -jar nb.jar --version`)
`3.1.153`
**Screenshots, if applicable**
If applicable, add screenshots to help explain your problem. N/A

**Comment by dave2wave** [comment]
@msmygit Is this still a concern?
