### ISSUE TITLE
HTTP driver GET command query argument being interpreted as a binding

### ISSUE THREAD

**Issue by jeromatron** [nosqlbench/nosqlbench#245]
Currently when trying to use a GET with the HTTP driver as well as query arguments, nosqlbench has trouble with thinking that the query parameter is a binding.

For example with the following:
```
  - tags:
      phase: main
      type: read-index
    params:
      ratio: <<read_ratio:1>>
    statements:
      - read: "GET http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}"
        Accept: "application/json"
        X-Cassandra-Request-Id: "{request_id}"
        X-Cassandra-Token: "<<auth_token:my_auth_token>>"
```

This throws the error:
```
00:43:18.760 [main] ERROR i.n.engine.core.ScenarioErrorHandler - Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'main-diag':
Binding named 'where' is not provided for template 'http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}'
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'main-diag':
Binding named 'where' is not provided for template 'http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}'
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:152)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:117)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:75)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:346)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:56)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'main-diag':
Binding named 'where' is not provided for template 'http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}'
	at io.nosqlbench.engine.core.script.Scenario.run(Scenario.java:268)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:296)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:47)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'main-diag':
Binding named 'where' is not provided for template 'http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}'
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:381)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:343)
	at java.scripting/javax.script.AbstractScriptEngine.eval(Unknown Source)
	at io.nosqlbench.engine.core.script.Scenario.run(Scenario.java:249)
	... 6 common frames omitted
Caused by: org.graalvm.polyglot.PolyglotException: Error initializing activity 'main-diag':
Binding named 'where' is not provided for template 'http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}'
	at io.nosqlbench.engine.core.ActivityExecutor.startActivity(ActivityExecutor.java:95)
	at io.nosqlbench.engine.core.ScenarioController.run(ScenarioController.java:90)
	at io.nosqlbench.engine.core.ScenarioController.run(ScenarioController.java:77)
	at io.nosqlbench.engine.core.ScenarioController.run(ScenarioController.java:102)
	at io.nosqlbench.engine.core.PolyglotScenarioController.run(PolyglotScenarioController.java:41)
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:345)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:379)
	... 9 common frames omitted
java.lang.RuntimeException: javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: Error initializing activity 'main-diag':
Binding named 'where' is not provided for template 'http://stargate:8082/v2/keyspaces/app/user?where={'userid':{'$eq':'19674593-43ef-4fdd-bdf4-98b19568b584'}}'
```

I try to escape the `?` symbol and that fails with a different error and I try to url encode the `?` symbol and that has a similar error.

**Comment by jeromatron** [comment]
When I try to URL encode the json, it also has a problem.  For example with this URL:

```
http://stargate:8082/v2/keyspaces/app/user?where=%7B%userid%27%3A%7B%27%24eq%27%3A%2719674593-43ef-4fdd-bdf4-98b19568b584%27%7D%7D
```

I get the following error:

```
{
    "description": "Server error: Input provided is not valid json",
    "code": 500
}
```

**Comment by jshook** [comment]
I think the URL encoding issue may be a server-side issue.
If the server is expected to take the result as valid JSON, then should also conform to standards for always URL decoding any URIs that are handed to it. When I URL Decode the encoded for above, I get the following:

```
{
  "refcode": {
    "$eq": "19674593-43ef-4fdd-bdf4-98b19568b584"
  }
}
```
Maybe something else is going on? We should check with the server devs.

**Comment by jshook** [comment]
These should be fixed in the latest nb4 pre-release.
