### ISSUE TITLE
NPE in http status code checking

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#265]
5635 ERROR [nb_setschema:001] CoreMotor    Error in core motor loop:java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.statusCode()" because "response" is null
java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.statusCode()" because "response" is null
	at io.nosqlbench.activitytype.http.HttpAction.runCycle(HttpAction.java:109)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

**Comment by jshook** [comment]
This should be fixed in the latest pre-release of nb4.
