### ISSUE TITLE
The jar getting generated after build is incompatible with windows

### ISSUE THREAD

**Issue by sourav11b** [nosqlbench/nosqlbench#284]
**Describe the bug**
I am building the project from windows using the command `mvn package -Dmaven.test.skip=true`. ( i tried both windows cmd and WSL1)

then when i try to run a test using `java -jar nb.jar run driver=cql yaml=nosqlbench.yaml tags=phase:main host=127.0.0.1 cycles=1000`

I am getting an error

`    539 ERROR [main] ScenarioErrorHandler internal error: 'posix:permissions' not supported as initial attribute
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at java.base/sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:494)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
        at java.base/java.nio.file.Files.createDirectories(Files.java:747)
        at io.nosqlbench.engine.cli.NBCLIOptions.setStatePath(NBCLIOptions.java:395)
        at io.nosqlbench.engine.cli.NBCLIOptions.parseGlobalOptions(NBCLIOptions.java:235)
        at io.nosqlbench.engine.cli.NBCLIOptions.<init>(NBCLIOptions.java:188)
        at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:94)
        at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:69)
'posix:permissions' not supported as initial attribute`

``
**To Reproduce**
1. described above

**What was Expected**
The test should run successfully. Jar files should be compatible across OSs

**Comment by adamfortuno** [comment]
I have the same issue.

**OS Name**: Microsoft Windows 10 Home
**OS Version**: 10.0.19043 Build 19043
**NoSQLBench** Version: 4.15.91
**Java Version**: 17.0.3.1

Steps to recreate...

```powershell
## Download and decompress Java
Invoke-WebRequest -OutFile -Uri "https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip"
Expand-Archive -Path ./java.zip -DestinationPath ./

## Add Java bin to the path
$java_path = $(ls jdk*).FullName
$env:PATH="${env:PATH};${java_path}\bin\"

##Verify version of Java and that it's in the path
java --version

## Download NoSQLWorkbecnh
Invoke-WebRequest -uri "https://github.com/nosqlbench/nosqlbench/releases/download/nosqlbench-4.15.91/nb.jar" -outfile "./nb.jar"

## Run NoSQLBench
java -jar ./nb.jar cql-iot astra `
secureconnectbundle=secure-connect-cudaenterprise.zip `
username=token `
password="AstraCS:boomChickaBoomBoom" `
keyspace=nosqlbench `
--show-stacktraces
```

I get a stack trace that looks like...

```powershell
2022-05-25 22:45:59,367 main ERROR Unable to locate appender "SCENARIO_APPENDER" for logger config "oshi.util"
    591 ERROR [main] ERRORHANDLER internal error: 'posix:permissions' not supported as initial attribute
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at java.base/sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
        at java.base/java.nio.file.Files.createDirectory(Files.java:700)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:753)
        at io.nosqlbench.engine.cli.NBCLIOptions.setStatePath(NBCLIOptions.java:434)
        at io.nosqlbench.engine.cli.NBCLIOptions.parseGlobalOptions(NBCLIOptions.java:254)
        at io.nosqlbench.engine.cli.NBCLIOptions.<init>(NBCLIOptions.java:207)
        at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:99)
        at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:66)
Scenario stopped due to error. See logs for details.
```

![image](https://user-images.githubusercontent.com/30395811/170405294-2b26b4c1-1b0d-4317-bcf7-44d73fa285e9.png)

**Comment by lingang881001** [comment]
finish?

**Comment by dave2wave** [comment]
This code has moved to NBStatePath and is protected by a try - catch:

**Comment by dave2wave** [comment]
Since the code has changed and this error is caught and explained this should be closed.
