### ISSUE TITLE
v4.15.44 not compatible with C* 4.0 RC1

### ISSUE THREAD

**Issue by grighetto** [nosqlbench/nosqlbench#316]
**Describe the bug**

NoSQLBench v4.15.44 cannot establish the control connection with C* 4.0 RC1. Stacktrace below.
I believe this is caused by the protocol changes in the new C* version and it will probably require a CQL driver upgrade in NoSQLBench. Specifically, it's probably being affected by this issue https://datastax-oss.atlassian.net/browse/JAVA-2936, although setting `protocol_version=V5` as a command-line param in nb didn't help.

**To Reproduce**

1. Try to run any activity against C* 4.0 RC1.

**What was Expected**

Successful connection with C* and no startup failures.

**Additional context**

OS: Linux
environment: k8s (GKE)
version info: 4.15.44

**Stacktrace**

```
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: target-dc2-service/10.232.3.3:9042 (com.datastax.driver.core.exceptions.TransportException: [target-dc2-service/10.232.3.3:9042] Connection has been closed), target-dc2-service/10.232.8.4:9042 (com.datastax.driver.core.exceptions.TransportException: [target-dc2-service/10.232.8.4:9042] Connection has been closed), target-dc2-service/10.232.2.4:9042 (com.datastax.driver.core.exceptions.TransportException: [target-dc2-service/10.232.2.4:9042] Connection has been closed))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:259)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:98)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1926)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1839)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:475)
	at com.datastax.driver.core.DelegatingCluster.getMetadata(DelegatingCluster.java:88)
	at io.nosqlbench.activitytype.cql.statements.core.CQLSessionCache.createSession(CQLSessionCache.java:324)
	at io.nosqlbench.activitytype.cql.statements.core.CQLSessionCache.lambda$getSession$0(CQLSessionCache.java:58)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at io.nosqlbench.activitytype.cql.statements.core.CQLSessionCache.getSession(CQLSessionCache.java:58)
	at io.nosqlbench.activitytype.cql.core.CqlActivity.getSession(CqlActivity.java:132)
	at io.nosqlbench.activitytype.cql.core.CqlActivity.initActivity(CqlActivity.java:113)
	at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.startActivity(ActivityExecutor.java:117)
```

**Comment by jshook** [comment]
The cqld3 version may work for this. It needs to be sanity checked. The cqld3 driver is the same code as used in the original cql driver, but with a newer (not v4) version of the Java client.

**Comment by sharadg** [comment]
@jshook - are there instructions on making cqld3 version work?

**Comment by jshook** [comment]
> @jshook - are there instructions on making cqld3 version work?

The only thing you should have to do is use `driver=cqld3` instead of `driver=cql`.

**Comment by grighetto** [comment]
With the `driver=cqld3` param I get a different error message:

```
Caused by: java.lang.RuntimeException: ActivityType 'cqld3' not found. Available types:webdriver,kafkaproducer,stdout,diag,tcpserver,tcpclient,http,jmx,dsegraph,cql,cqlverify,mongodb,pulsar,cockroachdb
	at io.nosqlbench.nb.api.spi.SimpleServiceLoader.lambda$getOrThrow$0(SimpleServiceLoader.java:47)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at io.nosqlbench.nb.api.spi.SimpleServiceLoader.getOrThrow(SimpleServiceLoader.java:45)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.getActivityExecutor(ScenarioController.java:305)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:115)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:96)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:130)
	at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:40)
```

**Comment by grighetto** [comment]
@jshook I noticed that FQCN `io.nosqlbench.activitytype.cql.core.CqlActivityType` is used in both `driver-cql-shaded` and `driver-cqld3-shaded`. I figured there could be some clashing during service loading so I renamed the activity type of CQL3 to be `Cql3ActivityType` and that at least made the `cqld3` type appear in the list of available drivers.
But after that, I was back to the original error around protocol versions. I tried upgrading the CQL3 driver to latest version (3.11.0) but that didn't help (I tried with `driver=cqld3 protocol_version=V5`).

I see there's already a 4.11.1 driver in maven central: https://search.maven.org/artifact/com.datastax.oss/java-driver-core/4.11.1/bundle, we should probably move to that.

**Comment by jshook** [comment]
The addition of the cql 4 driver is being worked on now with a couple other
important enhancements. We can't just drop it in, unfortunately, because it
changes the API so much that the previous code is no longer compatible with
it.

That is the reason the cqld3 driver was added recently, to provide a bridge
until the cqld4 driver is available. I can do more troubleshooting on the
cqld3 driver this week.

**Comment by grighetto** [comment]
I have a patch for this issue https://github.com/nosqlbench/nosqlbench/pull/318
The cqld3 module wasn't properly shaded and it was clashing with the old driver.

With the patch, I can connect to C* 4.0 RC1 with the `driver=cqld3` param.

**Comment by XN137** [comment]
great job!

 > I tried upgrading the CQL3 driver to latest version (3.11.0) 

would it be worthwhile to move that part out into a separate issue and do it anyway?

**Comment by jshook** [comment]
> great job!
> 
> > I tried upgrading the CQL3 driver to latest version (3.11.0)
> 
> would it be worthwhile to move that part out into a separate issue and do it anyway?

Yes, that would be great.

**Comment by jshook** [comment]
Thanks @grighetto ! I'm closing this one.
