### ISSUE TITLE
HTTP driver cannot resume work after server returns HTTP GO_AWAY

### ISSUE THREAD

**Issue by EricBorczuk** [nosqlbench/nosqlbench#401]
**Describe the bug**
While nosqlbench runs with the HTTP driver against Datastax Astra, the astra cluster will periodically issue a GO_AWAY, to tell the client to stop using its current connection and open up a new one. However, nosqlbench interprets the GO_AWAY signal as an error that should stop the scenario from running to completion, and it stops abruptly instead with an error:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: /192.168.0.131:64152: GOAWAY received
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.handlers.StopErrorHandler.handleError(StopErrorHandler.java:16)
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:52)
	at io.nosqlbench.activitytype.http.HttpAction.runCycle(HttpAction.java:130)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: /192.168.0.131:64152: GOAWAY received
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2086)
	at io.nosqlbench.activitytype.http.HttpAction.runCycle(HttpAction.java:94)
	... 4 more
Caused by: java.io.IOException: /192.168.0.131:64152: GOAWAY received
	at java.net.http/jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:999)
	at java.net.http/jdk.internal.net.http.Http2Connection.handleConnectionFrame(Http2Connection.java:867)
	at java.net.http/jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:738)
	at java.net.http/jdk.internal.net.http.frame.FramesDecoder.decode(FramesDecoder.java:155)
	at java.net.http/jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Http2Connection.java:232)
	at java.net.http/jdk.internal.net.http.Http2Connection.asyncReceive(Http2Connection.java:663)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1289)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.runOrSchedule(Http2Connection.java:1307)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1333)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1267)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:444)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	... 3 more
 401294 WARN  [scenarios:001] SCENARIO     Error in scenario, shutting down.
 401304 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread activities/documents-api/http-docsapi-crud-basic.yaml:001
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread activities/documents-api/http-docsapi-crud-basic.yaml:001
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:150)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:115)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:73)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:406)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:70)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread activities/documents-api/http-docsapi-crud-basic.yaml:001
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:319)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:374)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread activities/documents-api/http-docsapi-crud-basic.yaml:001
	at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.notifyException(ActivityExecutor.java:526)
	at io.nosqlbench.engine.core.lifecycle.ActivityExceptionHandler.uncaughtException(ActivityExceptionHandler.java:30)
	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1993)
Caused by: java.lang.RuntimeException: Error in activity thread activities/documents-api/http-docsapi-crud-basic.yaml:001
	... 3 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: /192.168.0.131:64152: GOAWAY received
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.handlers.StopErrorHandler.handleError(StopErrorHandler.java:16)
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:52)
	at io.nosqlbench.activitytype.http.HttpAction.runCycle(HttpAction.java:130)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: /192.168.0.131:64152: GOAWAY received
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2086)
	at io.nosqlbench.activitytype.http.HttpAction.runCycle(HttpAction.java:94)
	... 4 more
Caused by: java.io.IOException: /192.168.0.131:64152: GOAWAY received
	at java.net.http/jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:999)
	at java.net.http/jdk.internal.net.http.Http2Connection.handleConnectionFrame(Http2Connection.java:867)
	at java.net.http/jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:738)
	at java.net.http/jdk.internal.net.http.frame.FramesDecoder.decode(FramesDecoder.java:155)
	at java.net.http/jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Http2Connection.java:232)
	at java.net.http/jdk.internal.net.http.Http2Connection.asyncReceive(Http2Connection.java:663)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1289)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.runOrSchedule(Http2Connection.java:1307)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1333)
	at java.net.http/jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1267)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232)
	at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:444)
	at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	... 3 more
```

**To Reproduce**
1. Run `java -jar nb.jar run driver=http yaml=documents-api/http-docsapi-crud-basic.yaml protocol=https path_prefix='/api/rest' stargate_port=443 stargate_host='<valid astra host>' auth_token='<valid auth token>' tags=phase:main,type:write cycles=20000 threads=1`

**What was Expected**
Workload runs to completion

**Additional context**
OS: Windows, Linux (distribution), macOS ...
environment: k8s, docker, ...
version info (`./nb --version` or `java -jar nb.jar --version`)

**Screenshots, if applicable**

**Comment by jshook** [comment]
NB has configurable error handlers that can be mapped from exception types to handler verbs, but I don't think it will help in this case.

reference: [RFC-7540](https://datatracker.ietf.org/doc/html/rfc7540#page-43)

As described, _GOAWAY_ doesn't clarify to clients what kind of status (error or not) the server means, only that clients should not expect further streams to be processed on that connection. I think the Java HTTP client interprets this conservatively as an error, although it is unfortunately manifested as an IOException, and thus can't easily be handled in a specific way separately from other IOExceptions.

There is simply no way from the protocol spec to know if a client *should* attempt to reconnect and continue working. Further, there is no way for the server to know that a disconnection request *could* be graceful, as clients may reasonably assume sockets to be cache-able and reliable except in the case of a transport or server error. So, that puts us back at square one on whether this should be considered an error. My interpretation is that it *is* an error, in the sense that we had long-lived connection that unexpectedly was interrupted for some unknowable reason.

The JDK code does nothing different, and does not make this behavior adjustable:

```
            case GoAwayFrame.TYPE       -> handleGoAway((GoAwayFrame) frame);
    ...
    private void handleGoAway(GoAwayFrame frame)
        throws IOException
    {
        shutdown(new IOException(
                        String.valueOf(connection.channel().getLocalAddress())
                        +": GOAWAY received"));
    }
```

This suggests very strongly that we shouldn't expect users to treat this as a graceful reconnect either. At least, in one of the most pervasively available HTTP clients, it is implemented in a way that makes it (assuming GOAWAY to be a signal for a non-erroneous graceful disconnect and reconnect) a dubious client-side feature at best.

Yet, in this *specific* context we know it is part of a highly-available service, and thus we would normally reconnect in order to re-wire the client/session to an active endpoint. I think it is safe to assume that a "gracefully reconnect on GOAWAY" behavior is probably unlikely in practice. Instead, we should expect these cases to be handled as *retry*.

To emulate and test that behavior, we can use the nosqlbench error handler config.
Try `errors=count,retry` or if you just want to do this for IOExceptions, `errors=IOException:count,retry`

I've added a missing docs page for the error handler configuration here: 
[NoSQLBench Error Handlers](https://docs.nosqlbench.io/docs/reference/error-handlers/)

Please let me know if this addresses the issue.

**Comment by jshook** [comment]
@EricBorczuk It also occurs to me that the retry error handler might not be sufficient. In that case we may have to add an active reconnect capability to the HTTP driver, or at least something to invalidate the current client so that it will reinit as needed.

**Comment by EricBorczuk** [comment]
After rerunning with `errors=count, retry` I am getting benchmark results (it runs to completion) but only 11997/20000 cycles were successful, so I think what you said above is correct.

I actually also modified the code to force the HTTP client to use 1.1 instead of 2 - that "fixed" the goaway issue just by avoiding it altogether. Would you be against adding an option for http version, much like the option for `follow_redirects` that exists on the HTTP client?

**Comment by jshook** [comment]
That sounds like a helpful addition. I would also like to address this in the HTTP/2.0 mode but that is less urgent.

**Comment by mpenick** [comment]
@jshook In practice, GOAWAY is common (in fact many HTTP/2.0 servers send this every N requests for a persistent connection see http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests and http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests). The problem here is that `java.net.http.HttpClient` isn't a very good HTTP/2.0 client.  A good client like `OkHttp` (https://square.github.io/okhttp/) will just restart a new connection and send the next request on it in response to GOAWAY.

**Comment by jshook** [comment]
After more analysis, it appears that there is a specific type of change we can make to facilitate handling GOAWAY message.

Since the IOException does contain a marker for GOAWAY, we can synthesize a GoAwayReceived error which can allow for that to be marked for retry. Also, in the case that it is not intended to be tracked as an error when retries succeed here, we allow for an after-retries error count to be measured separately.

**Comment by kathirsvn** [comment]
@jshook I see your proposal for the fix. I would like to see if this (i.e. catch IOException and retry) is what is happening in other clients (okhttp or jetty) as well.

**Comment by jshook** [comment]
@kathirsvn It is not, specifically, because these clients are implemented at fundamentally different levels. Some of them have what you might call _transport_ or _connection pool_ management as additional features, such as automatically detecting a GOAWAY and re-initiating connections with the right message id offset to continue. Some _clients_ are simply to the spec, and don't include conventional work-arounds. The fundamental difference here is the level of implementation, although they are all just called "clients".

If we want the features of another http client, we can add a driver for it, but this would not be a quick solution unless it were contributed.
