### ISSUE TITLE
Inform the user that you can't use multiple Pulsar consumers with an exclusive subscription

### ISSUE THREAD

**Issue by mfleming** [nosqlbench/nosqlbench#405]
**What is the ideal scenario for using this feature?**

It would be helpful for users if they were told that using `threads= > 1` with an exclusive subscription type is incompatible. Today they just see a stacktrace when they use this config.

**Is your feature request related to a problem? Please describe.**

Right now, if a user tries to use multiple consumers (with nosqlbench's `threads=` param) on an exclusive subscription they see the following stacktrace:
```
    3425 WARN  [pulsar-client-io-5-1] ClientCnx    [id: 0x949c1aaa, L:/127.0.0.1:57660 - R:localhost/127.0.0.1:6650] Received error from server: Exclusive consumer is already connected
    3427 WARN  [pulsar-client-io-5-1] ConsumerImpl [persistent://public/default/foobar][nb] Failed to subscribe to topic on localhost/127.0.0.1:6650
org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: Exclusive consumer is already connected
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:991)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:97)
	at io.nosqlbench.driver.pulsar.PulsarSpace.getConsumer(PulsarSpace.java:440)
	at io.nosqlbench.driver.pulsar.ops.ReadyPulsarOp.lambda$resolveMsgConsume$52(ReadyPulsarOp.java:466)
	at io.nosqlbench.driver.pulsar.ops.PulsarConsumerMapper.apply(PulsarConsumerMapper.java:53)
	at io.nosqlbench.driver.pulsar.ops.PulsarConsumerMapper.apply(PulsarConsumerMapper.java:26)
	at io.nosqlbench.driver.pulsar.ops.ReadyPulsarOp.apply(ReadyPulsarOp.java:67)
	at io.nosqlbench.driver.pulsar.ops.ReadyPulsarOp.apply(ReadyPulsarOp.java:26)
	at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:41)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
    3460 INFO  [pulsar-client-io-5-1] Crc32cIntChecksum SSE4.2 CRC32C provider initialized
    3457 ERROR [pulsar_9dfd7719-b7c2-43b4-853e-f8604576d5db:002] CoreMotor    Error in core motor loop:java.lang.RuntimeException: java.lang.RuntimeException: Unable to create a Pulsar consumer!
```

This happens because the first thread "wins" the subscription and subsequent threads fail to create a consumer. 

**Would you like to help implementing or testing it?**

**Additional context**

**Comment by jshook** [comment]
Do we actually want to share the subscription across multiple threads in this case? If so, we can flag it in the op template (yaml) and create a concurrent hash map in the pulsar space. I'm not sure if this is desirable or not, but with synchronized access, it would certainly allow reader threads to go faster as a group.

**Comment by mfleming** [comment]
I think as a first step it would be simpler to just prohibit using multiple threads with an exclusive subscription, though you're right  that ideally we can use multiple threads to consume from an exclusive subscription.

But then since multiple threads is how we create multiple Pulsar consumers (there's no other special param for it) the semantics get a bit confusing if "multiple threads" triggers different behaviour for exclusive vs shared subscriptions?
