### ISSUE TITLE
imports field on fluent gremlin ops not being applied

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#422]
8691 ERROR [treechangegraphname_traversalclassicfluent_001:030] CoreMotor    Error in core motor loop:groovy.lang.MissingPropertyException: No such property: __ for class: Script1
groovy.lang.MissingPropertyException: No such property: __ for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at Script1.run(Script1.groovy:5)
	at io.nosqlbench.adapter.cqld4.opmappers.Cqld4FluentGraphOpDispenser.apply(Cqld4FluentGraphOpDispenser.java:46)
	at io.nosqlbench.adapter.cqld4.opmappers.Cqld4FluentGraphOpDispenser.apply(Cqld4FluentGraphOpDispenser.java:19)
	at io.nosqlbench.engine.api.activityimpl.uniform.StandardAction.runCycle(StandardAction.java:60)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

From an import with:

            imports:
              - "org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.__"

**Comment by jshook** [comment]
This was fixed in a recent release.
