### ISSUE TITLE
SSL regression since 4.15.65+

### ISSUE THREAD

**Issue by Pierrotws** [nosqlbench/nosqlbench#538]
**Describe the bug**
nosqlbench is not able to connect to SSL-ized DSE cluster with Self-Signed CA. 
Latest working version is 4.15.64

**To Reproduce**
1. Install DSE Cluster with Self signed CA
Use nosqlbench 4.15.65 to 4.15.89 :
```
java -jar nb.jar cql-iot driver=cql ssl=openssl caCertFilePath=master.cer  
```

this outputs:
```
     879 INFO  [main] NBCLI        Configured scenario log at logs/scenario_20220315_132439_493.log
     886 INFO  [main] NBCLI        Running NoSQLBench Version 4.15.89
     886 INFO  [main] NBCLI        command-line: cql-iot driver=cql ssl=openssl host=ip-10-101-32-250.srv101.dsinternal.org port=9042 caCertFilePath=ctool_security/master.cer -v
    1214 INFO  [main] NBCLI        client-hardware: {"processor-name":"Intel Xeon E3-12xx v2 (Ivy Bridge)","memory-GiB":"58.97","sockets":"32","logical-cores":"32","max-frequency-ghz":"1.70","physical-cores":"32","if-speeds":["0Mib","10Gib"],"heap-max-GiB":"14.75"}
    1214 INFO  [main] NBCLI        Docker metrics is enabled. Docker must be installed for this to work
    1672 INFO  [main] DockerMetricsManager preparing to start graphite exporter container...
    1910 INFO  [main] DockerHelper Starting docker with img=prom/graphite-exporter, tag=latest, name=graphite-exporter, ports=[9108, 9109], volumes=[/home/automaton/.nosqlbench/graphite-exporter/graphite_mapping.conf:/tmp/graphite_mapping.conf], env=[], cmds=[--graphite.mapping-config=/tmp/graphite_mapping.conf], reload=null
    2165 INFO  [main] DockerHelper The container graphite-exporter is already running
    2165 INFO  [main] DockerHelper Hupping config
    2166 INFO  [main] DockerMetricsManager graphite exporter container started
    2166 INFO  [main] DockerMetricsManager searching for graphite exporter container ip
    2169 INFO  [main] DockerHelper The container graphite-exporter is already running
    2169 INFO  [main] DockerHelper Hupping config
    2170 INFO  [main] DockerMetricsManager preparing to start docker metrics
    2170 INFO  [main] DockerHelper Starting docker with img=prom/prometheus, tag=latest, name=prom, ports=[9090], volumes=[/home/automaton/.nosqlbench/prometheus-conf:/etc/prometheus, /home/automaton/.nosqlbench/prometheus:/prometheus], env=null, cmds=[--config.file=/etc/prometheus/prometheus.yml, --storage.tsdb.path=/prometheus, --storage.tsdb.retention=183d, --web.enable-lifecycle], reload=http://localhost:9090/-/reload
    2175 INFO  [main] DockerHelper The container prom is already running
    2175 INFO  [main] DockerHelper Hupping config
    2364 INFO  [main] DockerMetricsManager prometheus started and listening
    2364 INFO  [main] DockerHelper Starting docker with img=grafana/grafana, tag=7.3.4, name=grafana, ports=[3000], volumes=[/home/automaton/.nosqlbench/grafana:/var/lib/grafana:rw], env=[GF_SECURITY_ADMIN_PASSWORD=admin, GF_AUTH_ANONYMOUS_ENABLED="true"], cmds=null, reload=null
    2369 INFO  [main] DockerHelper The container grafana is already running
    2369 INFO  [main] DockerHelper Hupping config
    2370 WARN  [main] NBCLI        Docker Containers are started, for grafana and prometheus, hit these urls in your browser: http://<host>:3000 and http://<host>:9090
    2490 INFO  [main] StrInterpolator removed template params after applying:{rampup-cycles=10000000, main-cycles=10000000, instrument=false, instrument-writes=false, instrument-reads=false, sources=10000, timespeed=100, stations=100, keyspace=baselines, rf=1, table=iot, compression=LZ4Compressor, expiry_minutes=60, write_cl=LOCAL_QUORUM, read_cl=LOCAL_QUORUM, read_ratio=1, limit=10, write_ratio=9}
    2578 INFO  [main] ANNOTATION   {"layer":"CLI","start":1647350681786,"end":1647350681786,"labels":{"layer":"CLI","session":"scenario_20220315_132439_493","span":"instant","appname":"nosqlbench"},"details":{"cli":"cql-iot\ndriver\u003dcql\nssl\u003dopenssl\nhost\u003dip-10-101-32-250.srv101.dsinternal.org\nport\u003d9042\ncaCertFilePath\u003dctool_security/master.cer\n-v"}}
    2646 INFO  [main] MetricReporters starting reporter: GraphiteReporter
    2650 INFO  [main] NBCLI        console logging level is INFO
    2662 INFO  [main] NBCLI        Charting disabled
    2666 INFO  [scenarios:001] ANNOTATION   {"layer":"Scenario","start":1647350681880,"end":1647350681880,"labels":{"layer":"Scenario","session":"scenario_20220315_132439_493","span":"instant","appname":"nosqlbench"},"details":{"engine":"Graalvm"}}
    3831 INFO  [scenarios:001] ANNOTATION   {"layer":"Activity","start":1647350683041,"end":1647350683041,"labels":{"layer":"Activity","alias":"cqliot_default_schema","session":"scenario_20220315_132439_493","span":"instant","appname":"nosqlbench"},"details":{"command":"run","params":"ActivityDef:(1)/{driver\u003dcql, port\u003d9042, hosts\u003dip-10-101-32-250.srv101.dsinternal.org, threads\u003d1, caCertFilePath\u003dctool_security/master.cer, workload\u003dcql-iot, alias\u003dcqliot_default_schema, ssl\u003dopenssl, tags\u003dphase:schema}"}}
    3908 INFO  [scenarios:001] ActivityExecutor starting activity cqliot_default_schema for cycles [0..0)=0
    3909 INFO  [scenarios:001] ANNOTATION   {"layer":"Activity","start":1647350683124,"end":1647350683124,"labels":{"layer":"Activity","alias":"cqliot_default_schema","driver":"cql","workload":"cql-iot","session":"scenario_20220315_132439_493","span":"instant","appname":"nosqlbench"},"details":{"params":"ActivityDef:(1)/{driver\u003dcql, port\u003d9042, hosts\u003dip-10-101-32-250.srv101.dsinternal.org, threads\u003d1, caCertFilePath\u003dctool_security/master.cer, workload\u003dcql-iot, alias\u003dcqliot_default_schema, ssl\u003dopenssl, tags\u003dphase:schema}"}}
    3963 INFO  [scenarios:001] core         DataStax Java Driver 1.9.0 for DataStax Enterprise (DSE) and Apache Cassandra®
    3971 INFO  [scenarios:001] GuavaCompatibility Detected Guava >= 19 in the classpath, using modern compatibility layer
    3984 INFO  [scenarios:001] CQLSessionCache Using driver type 'DSE'
    4000 INFO  [scenarios:001] PARAMS       removing param: caCertFilePath
    4003 INFO  [scenarios:001] CQLSessionCache Using driver type 'DSE'
    4004 INFO  [scenarios:001] PARAMS       removing param: ssl
    4004 INFO  [scenarios:001] CQLSessionCache Using driver type 'DSE'
    4175 INFO  [scenarios:001] ClockFactory Using native clock to generate timestamps.
    4406 INFO  [scenarios:001] UUIDs        PID obtained through native call to getpid(): 24237
    4659 INFO  [scenarios:001] NettyUtil    Found Netty's native epoll transport in the classpath, using it
    4970 WARN  [scenarios:001] SCENARIO     Error in scenario, shutting down.
    4972 INFO  [scenarios:001] ActivityExecutor stopping activity CQLActivity {activityDef=ActivityDef:(3)/{driver=cql, port=9042, hosts=ip-10-101-32-250.srv101.dsinternal.org, threads=1, workload=cql-iot, alias=cqliot_default_schema, tags=phase:schema}, session=null, opSequence=null}
    5078 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error initializing activity 'cqliot_default_schema':
All host(s) tried for query failed (tried: ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042 (com.datastax.driver.core.exceptions.TransportException: [ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042] Connection has been closed))
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error initializing activity 'cqliot_default_schema':
All host(s) tried for query failed (tried: ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042 (com.datastax.driver.core.exceptions.TransportException: [ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042] Connection has been closed))
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:150)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:115)
	at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:73)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:411)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:66)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error initializing activity 'cqliot_default_schema':
All host(s) tried for query failed (tried: ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042 (com.datastax.driver.core.exceptions.TransportException: [ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042] Connection has been closed))
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:319)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:374)
	at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: java.lang.RuntimeException: Error initializing activity 'cqliot_default_schema':
All host(s) tried for query failed (tried: ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042 (com.datastax.driver.core.exceptions.TransportException: [ip-10-101-32-250.srv101.dsinternal.org/10.101.32.250:9042] Connection has been closed))
	at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.startActivity(ActivityExecutor.java:119)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:120)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:98)
	at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:132)
	at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:40)
	at <js>.:program(<eval>:1)
	at org.graalvm.polyglot.Context.eval(Context.java:347)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:429)
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:371)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:247)
	at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:299)
```

Version up to 4.15.64 works well.

**Comment by jshook** [comment]
Leaving this open until someone reports a UAT-level verification that you can configure an Apache Cassandra or DSE instance with default SSL settings and connect to it with a recent stable release.

**Comment by jshook** [comment]
No new reports of this issue in awhile, and we are pretty confident that is is working well from UAT.
