### ISSUE TITLE
Failure to run `nb.jar` on MacOS

### ISSUE THREAD

**Issue by tatu-at-datastax** [nosqlbench/nosqlbench#586]
When trying to use `nb.jar` (either built locally or downloading latest release, currently `4.15.93`) on MacOS, I get stack trace like:

```
bin % java -jar ./nb-4.15.93.jar --list-drivers

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'IOKit':
dlopen(libIOKit.dylib, 9): image not found
dlopen(libIOKit.dylib, 9): image not found
Native library (darwin/libIOKit.dylib) not found in resource path (./nb-4.15.93.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at com.sun.jna.platform.mac.IOKit.<clinit>(IOKit.java:51)
	at com.sun.jna.platform.mac.IOKitUtil.<clinit>(IOKitUtil.java:39)
	at oshi.hardware.platform.mac.MacCentralProcessor.queryArmCpu(MacCentralProcessor.java:262)
	at oshi.hardware.platform.mac.MacCentralProcessor.initProcessorCounts(MacCentralProcessor.java:142)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:64)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createProcessor(MacHardwareAbstractionLayer.java:61)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)
	at io.nosqlbench.nb.api.metadata.SystemId.getHostSummary(SystemId.java:81)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:128)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:66)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libIOKit.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 16 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libIOKit.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 16 more
	Suppressed: java.io.IOException: Native library (darwin/libIOKit.dylib) not found in resource path (./nb-4.15.93.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 16 more
```

the only invocation that succeeds is one without arguments; any command-line arguments trigger this exception.

**Comment by tatu-at-datastax** [comment]
Trying out older versions it looks like this is a recent breakage: version `4.15.91` seems to work.

**Comment by jshook** [comment]
Thanks, I'll compare the changes from there.

**Comment by jshook** [comment]
@tatu-at-datastax The changes in 4.15.92 and 4.15.93 were specifically to address incompatibility with Mac M1 architecture and the OSHI library. I will likely put safety wrappers around these calls with a warning rather than making this critical-path to run NB. (These are advisory details which help tremendously in scoping issues, so they are useful enough to have, but not critical.)

Alas, the updates didn't help with the Mac m1 and furthermore they broke other Macs. I'll add an optional wrapper around them to get users unblocked first.

**Comment by tatu-at-datastax** [comment]
Thank you @jshook!

**Comment by tatu-at-datastax** [comment]
This fails for me on Intel Mac with:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/unix/LibCAPI$size_t$ByReference
	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:61)
	at oshi.hardware.platform.mac.MacCentralProcessor.initProcessorCounts(MacCentralProcessor.java:131)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:64)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createProcessor(MacHardwareAbstractionLayer.java:61)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)
	at io.nosqlbench.nb.api.metadata.SystemId.lambda$getHostSummary$5(SystemId.java:118)
	at io.nosqlbench.nb.api.metadata.SystemId$HardwareSummary.add(SystemId.java:179)
	at io.nosqlbench.nb.api.metadata.SystemId.getHostSummary(SystemId.java:117)
	at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:146)
	at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:84)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.unix.LibCAPI$size_t$ByReference
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

```

**Comment by tatu-at-datastax** [comment]
Correct, this was resolved. Thank you!
