### ISSUE TITLE
Pulsar, batch-msg-send-start operation fails due to NullPointerException

### ISSUE THREAD

**Issue by mac89** [nosqlbench/nosqlbench#678]
**Describe the bug**
Trying to run the optype `batch-msg-send-start` using the [provided example](https://docs.nosqlbench.io/docs/drivers/pulsar/#54-batch-producer-command-block-only-applicable-with-pulsar-synchronous-api) results in a NullPointerException

**To Reproduce**
1. Use this `activities/batch-producer.yaml`:
```yaml
scenarios:
  small:
    - run driver=pulsar service_url=pulsar+ssl://my.pulsar.com:6651 web_url=https://my.pulsar.com:8443
      tags=phase:batch-producer cycles=10k threads=2
  large:
    - run driver=pulsar service_url=pulsar+ssl://my.pulsar.com:6651 web_url=https://my.pulsar.com:8443
      tags=phase:batch-producer cycles=1m threads=2

bindings:
  # message key, property and value
  mykey: ToUUID();ToString();
  myprop1: ToDateTime();
  sensor_id: ToInt(6);
  myprop2: ToBoolean();
  reading_time: ToDateTime();
  reading_value: ToFloat();
  core_topic_name: Mod(5); ToString(); Prefix("t")

# document level parameters that apply to all Pulsar client types:
params:
  topic_uri: "persistent://eu-crit-prd/benchmark/{core_topic_name}"
  async_api: "false"
  seq_tracking: "true"

blocks:
  - name: batch-producer-block
    tags:
      phase: batch-producer
    statements:
      - name: s1
        optype: batch-msg-send-start
        # For batch producer, "producer_name" should be associated with batch start
        # batch_producer_name: {batch_producer_name}
        ratio: 1
      - name: s2
        optype: batch-msg-send
        msg_key: "{mykey}"
        msg_property: |
          {
            "prop1": "{myprop1}",
            "prop2": "{myprop2}"
          }
        msg_value: |
          {
              "SensorID": "{sensor_id}",
              "SensorType": "Temperature",
              "ReadingTime": "{reading_time}",
              "ReadingValue": {reading_value}
          }
        ratio: 100
      - name: s3
        optype: batch-msg-send-end
        ratio: 1
```
2. Run using `./nb ./activities/batch-producer small -v`

**What was Expected**
No exceptions to be thrown

**Additional context**
```shell
    1410 INFO  [main] NBCLI        Configured scenario log at logs/scenario_20220727_091913_978.log
    1418 INFO  [main] NBCLI        Running NoSQLBench Version 4.15.101
    1418 INFO  [main] NBCLI        command-line: ./activities/batch-producer small -v
    1948 INFO  [main] NBCLI        client-hardware: {"physical-cores":"4","logical-cores":"4","max-frequency-ghz":"0.00","sockets":"1","processor-name":"AMD Ryzen 7 4700U with Radeon Graphics","memory-GiB":"9.72","heap-max-GiB":"2.43","if-speeds":"[10Gib]"}
    2330 INFO  [main] StrInterpolator removed template params after applying:{}
    2403 INFO  [main] ANNOTATION   {"layer":"CLI","start":1658906355797,"end":1658906355797,"labels":{"layer":"CLI","session":"scenario_20220727_091913_978","span":"instant","appname":"nosqlbench"},"details":{"cli":"./activities/batch-producer\nsmall\n-v"}}
    2406 INFO  [main] NBCLI        console logging level is INFO
    2451 INFO  [main] NBCLI        Charting disabled
    2498 INFO  [scenarios:001] ANNOTATION   {"layer":"Scenario","start":1658906355898,"end":1658906355898,"labels":{"layer":"Scenario","session":"scenario_20220727_091913_978","span":"instant","appname":"nosqlbench"},"details":{"engine":"Graalvm"}}
    4460 INFO  [scenarios:001] ANNOTATION   {"layer":"Activity","start":1658906357853,"end":1658906357853,"labels":{"layer":"Activity","alias":"batchproducer_small_000","session":"scenario_20220727_091913_978","span":"instant","appname":"nosqlbench"},"details":{"command":"run","params":"ActivityDef:(1)/{service_url\u003dpulsar+ssl://my.pulsar.com:6651, driver\u003dpulsar, web_url\u003dhttps://my.pulsar.com:8443, threads\u003d2, workload\u003d./activities/batch-producer, alias\u003dbatchproducer_small_000, cycles\u003d10k, tags\u003dphase:batch-producer}"}}
    4554 INFO  [scenarios:001] ActivityExecutor starting activity batchproducer_small_000 for cycles [0..10000)=10000
    4555 INFO  [scenarios:001] ANNOTATION   {"layer":"Activity","start":1658906357956,"end":1658906357956,"labels":{"layer":"Activity","alias":"batchproducer_small_000","driver":"pulsar","workload":"./activities/batch-producer","session":"scenario_20220727_091913_978","span":"instant","appname":"nosqlbench"},"details":{"params":"ActivityDef:(1)/{service_url\u003dpulsar+ssl://my.pulsar.com:6651, driver\u003dpulsar, web_url\u003dhttps://my.pulsar.com:8443, threads\u003d2, workload\u003d./activities/batch-producer, alias\u003dbatchproducer_small_000, cycles\u003d10k, tags\u003dphase:batch-producer}"}}
    5725 WARN  [scenarios:001] SecurityUtility Conscrypt isn't available. Using JDK default security provider.
java.lang.ClassNotFoundException: org.conscrypt.Conscrypt
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at org.apache.pulsar.common.util.SecurityUtility.loadConscryptProvider(SecurityUtility.java:122)
        at org.apache.pulsar.common.util.SecurityUtility.<clinit>(SecurityUtility.java:79)
        at org.apache.pulsar.client.impl.auth.AuthenticationDataTls.<init>(AuthenticationDataTls.java:56)
        at org.apache.pulsar.client.impl.auth.AuthenticationTls.getAuthData(AuthenticationTls.java:86)
        at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.<init>(AsyncHttpConnector.java:120)
        at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnectorProvider.getConnector(AsyncHttpConnectorProvider.java:52)
        at org.apache.pulsar.client.admin.internal.PulsarAdminImpl.<init>(PulsarAdminImpl.java:200)
        at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:47)
        at io.nosqlbench.driver.pulsar.PulsarActivity.initPulsarAdminAndClientObj(PulsarActivity.java:246)
        at io.nosqlbench.driver.pulsar.PulsarActivity.initActivity(PulsarActivity.java:137)
        at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.startActivity(ActivityExecutor.java:116)
        at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:120)
        at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:98)
        at io.nosqlbench.engine.core.lifecycle.ScenarioController.run(ScenarioController.java:132)
        at io.nosqlbench.engine.core.lifecycle.PolyglotScenarioController.run(PolyglotScenarioController.java:58)
        at com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MHBase.invokeHandle(HostMethodDesc.java:292)
        at com.oracle.truffle.polyglot.HostToGuestCodeCache$1.executeImpl(HostToGuestCodeCache.java:86)
        at com.oracle.truffle.polyglot.GuestToHostRootNode.execute(GuestToHostRootNode.java:82)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
        at com.oracle.truffle.api.impl.DefaultRuntimeAccessor$DefaultRuntimeSupport.callInlined(DefaultRuntimeAccessor.java:114)
        at com.oracle.truffle.polyglot.GuestToHostRootNode.guestToHostCall(GuestToHostRootNode.java:108)
        at com.oracle.truffle.polyglot.HostMethodDesc$SingleMethod$MHBase.invokeGuestToHost(HostMethodDesc.java:319)
        at com.oracle.truffle.polyglot.HostExecuteNode.doInvoke(HostExecuteNode.java:811)
        at com.oracle.truffle.polyglot.HostExecuteNode.doOverloadedCached(HostExecuteNode.java:241)
        at com.oracle.truffle.polyglot.HostExecuteNodeGen.executeAndSpecialize(HostExecuteNodeGen.java:241)
        at com.oracle.truffle.polyglot.HostExecuteNodeGen.execute(HostExecuteNodeGen.java:94)
        at com.oracle.truffle.polyglot.HostObject.invokeMember(HostObject.java:412)
        at com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMemberNode_AndSpecialize(HostObjectGen.java:1390)
        at com.oracle.truffle.polyglot.HostObjectGen$InteropLibraryExports$Cached.invokeMember(HostObjectGen.java:1362)
        at com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:5989)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$ForeignInvokeNode.executeCall(JSFunctionCallNode.java:1481)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeAndSpecialize(JSFunctionCallNode.java:292)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:238)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$InvokeNode.execute(JSFunctionCallNode.java:721)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic4(JSWriteCurrentFrameSlotNodeGen.java:154)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:80)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:302)
        at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:124)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:73)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:147)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:93)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
        at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:59)
        at com.oracle.truffle.js.lang.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:214)
        at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:84)
        at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:99)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:941)
        at org.graalvm.polyglot.Context.eval(Context.java:347)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:429)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:371)
        at java.scripting/javax.script.AbstractScriptEngine.eval(Unknown Source)
        at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:299)
        at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:374)
        at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:56)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
    6494 INFO  [scenarios:001] StrInterpolator removed template params after applying:{}
    8147 INFO  [scenarios:001] ReadyPulsarOp topic_uri: persistent://eu-crit-prd/benchmark/t0
    8150 INFO  [scenarios:001] ReadyPulsarOp async_api: false
    8171 INFO  [scenarios:001] ReadyPulsarOp use_transaction: false
    8172 INFO  [scenarios:001] ReadyPulsarOp admin_delop: false
    8173 INFO  [scenarios:001] ReadyPulsarOp seq_tracking: true
    8174 INFO  [scenarios:001] ReadyPulsarOp payload_rtt_field_func: 
    8306 INFO  [scenarios:001] ReadyPulsarOp topic_uri: persistent://eu-crit-prd/benchmark/t0
    8306 INFO  [scenarios:001] ReadyPulsarOp async_api: false
    8306 INFO  [scenarios:001] ReadyPulsarOp use_transaction: false
    8306 INFO  [scenarios:001] ReadyPulsarOp admin_delop: false
    8306 INFO  [scenarios:001] ReadyPulsarOp seq_tracking: true
    8307 INFO  [scenarios:001] ReadyPulsarOp payload_rtt_field_func: 
    8454 INFO  [scenarios:001] ReadyPulsarOp topic_uri: persistent://eu-crit-prd/benchmark/t0
    8454 INFO  [scenarios:001] ReadyPulsarOp async_api: false
    8454 INFO  [scenarios:001] ReadyPulsarOp use_transaction: false
    8455 INFO  [scenarios:001] ReadyPulsarOp admin_delop: false
    8455 INFO  [scenarios:001] ReadyPulsarOp seq_tracking: true
    8455 INFO  [scenarios:001] ReadyPulsarOp payload_rtt_field_func: 
    8466 INFO  [scenarios:001] ACTIVITY     defaulting stride to 102 (the sequence length)
    8473 WARN  [scenarios:001] ACTIVITY     The stride does not evenly divide cycles. Only full strides will be executed,leaving some cycles unused. (stride=102, cycles=10000)
    8475 INFO  [scenarios:001] ACTIVITY     setting threads to 2 (direct)
    8825 INFO  [pulsar-client-io-5-1] ConnectionPool [[id: 0xcc88869e, L:/*.*.*.*:52278 - R:my.pulsar.com/*.*.*.*:6651]] Connected to server
    9259 INFO  [pulsar-client-io-5-1] ProducerStatsRecorderImpl Starting Pulsar producer perf with config: {
  "topicName" : "persistent://eu-crit-prd/benchmark/t0",
  "producerName" : null,
  "sendTimeoutMs" : 60000,
  "blockIfQueueFull" : true,
  "maxPendingMessages" : 10000,
  "maxPendingMessagesAcrossPartitions" : 50000,
  "messageRoutingMode" : "RoundRobinPartition",
  "hashingScheme" : "JavaStringHash",
  "cryptoFailureAction" : "FAIL",
  "batchingMaxPublishDelayMicros" : 1000,
  "batchingPartitionSwitchFrequencyByPublishDelay" : 10,
  "batchingMaxMessages" : 1000,
  "batchingMaxBytes" : 131072,
  "batchingEnabled" : true,
  "chunkingEnabled" : false,
  "compressionType" : "NONE",
  "initialSequenceId" : null,
  "autoUpdatePartitions" : true,
  "autoUpdatePartitionsIntervalSeconds" : 60,
  "multiSchema" : true,
  "accessMode" : "Shared",
  "properties" : { }
}
    9275 INFO  [pulsar-client-io-5-1] ProducerStatsRecorderImpl Pulsar client config: {
  "serviceUrl" : "pulsar+ssl://my.pulsar.com:6651",
  "authPluginClassName" : "org.apache.pulsar.client.impl.auth.AuthenticationTls",
  "authParams" : "*****",
  "authParamMap" : null,
  "operationTimeoutMs" : 30000,
  "statsIntervalSeconds" : 60,
  "numIoThreads" : 1,
  "numListenerThreads" : 1,
  "connectionsPerBroker" : 1,
  "useTcpNoDelay" : true,
  "useTls" : true,
  "tlsTrustCertsFilePath" : "/etc/pulsar/certs/benchmark/pulsar-ca.crt",
  "tlsAllowInsecureConnection" : false,
  "tlsHostnameVerificationEnable" : true,
  "concurrentLookupRequest" : 5000,
  "maxLookupRequest" : 50000,
  "maxLookupRedirects" : 20,
  "maxNumberOfRejectedRequestPerConnection" : 50,
  "keepAliveIntervalSeconds" : 30,
  "connectionTimeoutMs" : 5000,
  "requestTimeoutMs" : 60000,
  "initialBackoffIntervalNanos" : 100000000,
  "maxBackoffIntervalNanos" : 60000000000,
  "enableBusyWait" : false,
  "listenerName" : null,
  "useKeyStoreTls" : false,
  "sslProvider" : null,
  "tlsTrustStoreType" : "JKS",
  "tlsTrustStorePath" : null,
  "tlsTrustStorePassword" : null,
  "tlsCiphers" : [ ],
  "tlsProtocols" : [ ],
  "memoryLimitBytes" : 0,
  "proxyServiceUrl" : null,
  "proxyProtocol" : null,
  "enableTransaction" : false
}
    9295 INFO  [pulsar-client-io-5-1] ProducerStatsRecorderImpl Starting Pulsar producer perf with config: {
  "topicName" : "persistent://eu-crit-prd/benchmark/t2",
  "producerName" : null,
  "sendTimeoutMs" : 60000,
  "blockIfQueueFull" : true,
  "maxPendingMessages" : 10000,
  "maxPendingMessagesAcrossPartitions" : 50000,
  "messageRoutingMode" : "RoundRobinPartition",
  "hashingScheme" : "JavaStringHash",
  "cryptoFailureAction" : "FAIL",
  "batchingMaxPublishDelayMicros" : 1000,
  "batchingPartitionSwitchFrequencyByPublishDelay" : 10,
  "batchingMaxMessages" : 1000,
  "batchingMaxBytes" : 131072,
  "batchingEnabled" : true,
  "chunkingEnabled" : false,
  "compressionType" : "NONE",
  "initialSequenceId" : null,
  "autoUpdatePartitions" : true,
  "autoUpdatePartitionsIntervalSeconds" : 60,
  "multiSchema" : true,
  "accessMode" : "Shared",
  "properties" : { }
}
    9304 INFO  [pulsar-client-io-5-1] ProducerStatsRecorderImpl Pulsar client config: {
  "serviceUrl" : "pulsar+ssl://my.pulsar.com:6651",
  "authPluginClassName" : "org.apache.pulsar.client.impl.auth.AuthenticationTls",
  "authParams" : "*****",
  "authParamMap" : null,
  "operationTimeoutMs" : 30000,
  "statsIntervalSeconds" : 60,
  "numIoThreads" : 1,
  "numListenerThreads" : 1,
  "connectionsPerBroker" : 1,
  "useTcpNoDelay" : true,
  "useTls" : true,
  "tlsTrustCertsFilePath" : "/etc/pulsar/certs/benchmark/pulsar-ca.crt",
  "tlsAllowInsecureConnection" : false,
  "tlsHostnameVerificationEnable" : true,
  "concurrentLookupRequest" : 5000,
  "maxLookupRequest" : 50000,
  "maxLookupRedirects" : 20,
  "maxNumberOfRejectedRequestPerConnection" : 50,
  "keepAliveIntervalSeconds" : 30,
  "connectionTimeoutMs" : 5000,
  "requestTimeoutMs" : 60000,
  "initialBackoffIntervalNanos" : 100000000,
  "maxBackoffIntervalNanos" : 60000000000,
  "enableBusyWait" : false,
  "listenerName" : null,
  "useKeyStoreTls" : false,
  "sslProvider" : null,
  "tlsTrustStoreType" : "JKS",
  "tlsTrustStorePath" : null,
  "tlsTrustStorePassword" : null,
  "tlsCiphers" : [ ],
  "tlsProtocols" : [ ],
  "memoryLimitBytes" : 0,
  "proxyServiceUrl" : null,
  "proxyProtocol" : null,
  "enableTransaction" : false
}
    9328 INFO  [pulsar-client-io-5-1] ConnectionPool [[id: 0xf3972435, L:/*.*.*.*:52280 - R:my.pulsar.com/*.*.*.*:6651]] Connected to server
    9330 INFO  [pulsar-client-io-5-1] ClientCnx    [id: 0xf3972435, L:/*.*.*.*:52280 - R:my.pulsar.com/*.*.*.*:6651] Connected through proxy to target broker at 172.30.17.24:6651
    9350 INFO  [pulsar-client-io-5-1] ConnectionPool [[id: 0xa59d2e29, L:/*.*.*.*:52282 - R:my.pulsar.com/*.*.*.*:6651]] Connected to server
    9353 INFO  [pulsar-client-io-5-1] ClientCnx    [id: 0xa59d2e29, L:/*.*.*.*:52282 - R:my.pulsar.com/*.*.*.*:6651] Connected through proxy to target broker at 172.30.17.25:6651
    9675 INFO  [pulsar-client-io-5-1] ProducerImpl [persistent://eu-crit-prd/benchmark/t0] [null] Creating producer on cnx [id: 0xf3972435, L:/*.*.*.*:52280 - R:my.pulsar.com/*.*.*.*:6651]
    9767 INFO  [pulsar-client-io-5-1] ProducerImpl [persistent://eu-crit-prd/benchmark/t2] [null] Creating producer on cnx [id: 0xa59d2e29, L:/*.*.*.*:52282 - R:my.pulsar.com/*.*.*.*:6651]
    9955 INFO  [pulsar-client-io-5-1] ProducerImpl [persistent://eu-crit-prd/benchmark/t0] [ams1-24-654] Created producer on cnx [id: 0xf3972435, L:/*.*.*.*:52280 - R:my.pulsar.com/*.*.*.*:6651]
   10025 INFO  [pulsar-client-io-5-1] ProducerImpl [persistent://eu-crit-prd/benchmark/t2] [ams1-25-552] Created producer on cnx [id: 0xa59d2e29, L:/*.*.*.*:52282 - R:my.pulsar.com/*.*.*.*:6651]
   10405 INFO  [pulsar-client-io-5-1] Crc32cIntChecksum SSE4.2 CRC32C provider initialized
   10451 ERROR [batchproducer_small_000:002] CoreMotor    Error in core motor loop:java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.handlers.StopErrorHandler.handleError(StopErrorHandler.java:34)
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:70)
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:78)
        at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
        at io.nosqlbench.driver.pulsar.ops.PulsarBatchProducerOp.run(PulsarBatchProducerOp.java:83)
        at io.nosqlbench.driver.pulsar.ops.SyncPulsarOp.run(SyncPulsarOp.java:28)
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:73)
        ... 4 more
   10451 ERROR [batchproducer_small_000:001] CoreMotor    Error in core motor loop:java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.handlers.StopErrorHandler.handleError(StopErrorHandler.java:34)
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:70)
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:78)
        at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
        at io.nosqlbench.driver.pulsar.ops.PulsarBatchProducerOp.run(PulsarBatchProducerOp.java:83)
        at io.nosqlbench.driver.pulsar.ops.SyncPulsarOp.run(SyncPulsarOp.java:28)
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:73)
        ... 4 more
   10453 INFO  [batchproducer_small_000:002] ActivityExecutor stopping activity batchproducer_small_000
   10461 INFO  [batchproducer_small_000:002] ProducerStatsRecorderImpl [persistent://eu-crit-prd/benchmark/t0] [ams1-24-654] Pending messages: 1 --- Publish throughput: 1.69 msg/s --- 0.00 Mbit/s --- Latency: med: 67.000 ms - 95pct: 67.000 ms - 99pct: 67.000 ms - 99.9pct: 67.000 ms - max: 67.000 ms --- Ack received rate: 0.85 ack/s --- Failed messages: 0
   10462 INFO  [scenarios:001] ProducerStatsRecorderImpl [persistent://eu-crit-prd/benchmark/t2] [ams1-25-552] Pending messages: 0 --- Publish throughput: 1.74 msg/s --- 0.00 Mbit/s --- Latency: med: 66.000 ms - 95pct: 66.000 ms - 99pct: 66.000 ms - 99.9pct: 66.000 ms - max: 66.000 ms --- Ack received rate: 0.87 ack/s --- Failed messages: 0
   10479 INFO  [pulsar-client-io-5-1] ProducerImpl [persistent://eu-crit-prd/benchmark/t2] [ams1-25-552] Closed Producer
   10483 INFO  [pulsar-client-io-5-1] ProducerImpl [persistent://eu-crit-prd/benchmark/t0] [ams1-24-654] Closed Producer
   10492 INFO  [batchproducer_small_000:002] PulsarClientImpl Client closing. URL: pulsar+ssl://my.pulsar.com:6651
   10494 INFO  [scenarios:001] PulsarClientImpl Client closing. URL: pulsar+ssl://my.pulsar.com:6651
   10500 INFO  [pulsar-client-io-5-1] ClientCnx    [id: 0xcc88869e, L:/*.*.*.*:52278 ! R:my.pulsar.com/*.*.*.*:6651] Disconnected
   10507 INFO  [pulsar-client-io-5-1] ClientCnx    [id: 0xf3972435, L:/*.*.*.*:52280 ! R:my.pulsar.com/*.*.*.*:6651] Disconnected
   10508 WARN  [scenarios:001] SCENARIO     Error in scenario, shutting down.
   10508 INFO  [pulsar-client-io-5-1] ClientCnx    [id: 0xa59d2e29, L:/*.*.*.*:52282 ! R:my.pulsar.com/*.*.*.*:6651] Disconnected
   12532 INFO  [scenarios:001] ActivityExecutor stopping activity batchproducer_small_000
   12533 INFO  [scenarios:001] PulsarClientImpl Client closing. URL: pulsar+ssl://my.pulsar.com:6651
   12535 INFO  [batchproducer_small_000:001] ActivityExecutor stopping activity batchproducer_small_000
   12535 INFO  [batchproducer_small_000:001] PulsarClientImpl Client closing. URL: pulsar+ssl://my.pulsar.com:6651
   12587 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
        at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
        at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:150)
        at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:115)
        at io.nosqlbench.engine.core.script.ScenariosExecutor.awaitAllResults(ScenariosExecutor.java:73)
        at io.nosqlbench.engine.cli.NBCLI.run(NBCLI.java:429)
        at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:84)
Caused by: java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
        at io.nosqlbench.engine.core.script.Scenario.runScenario(Scenario.java:319)
        at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:374)
        at io.nosqlbench.engine.core.script.Scenario.call(Scenario.java:56)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
        at io.nosqlbench.engine.core.lifecycle.ActivityExecutor.notifyException(ActivityExecutor.java:526)
        at io.nosqlbench.engine.core.lifecycle.ActivityExceptionHandler.uncaughtException(ActivityExceptionHandler.java:30)
        at java.base/java.lang.Thread.dispatchUncaughtException(Unknown Source)
Caused by: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
        ... 3 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.handlers.StopErrorHandler.handleError(StopErrorHandler.java:34)
        at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:70)
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:78)
        at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:405)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "container" is null
        at io.nosqlbench.driver.pulsar.ops.PulsarBatchProducerOp.run(PulsarBatchProducerOp.java:83)
        at io.nosqlbench.driver.pulsar.ops.SyncPulsarOp.run(SyncPulsarOp.java:28)
        at io.nosqlbench.driver.pulsar.PulsarAction.runCycle(PulsarAction.java:73)
        ... 4 more
   12590 ERROR [main] ERRORHANDLER cause (see stack trace for details):javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
java.lang.RuntimeException: javax.script.ScriptException: java.lang.RuntimeException: Error in activity thread batchproducer_small_000:002
   12591 WARN  [Thread-1] SCENARIO     Scenario was interrupted by process exit, shutting down
   12592 INFO  [Thread-1] SCENARIO     scenario state: Interrupted
   12593 INFO  [Thread-1] ANNOTATION   {"layer":"Scenario","start":1658906355898,"end":1658906365993,"labels":{"layer":"Scenario","state":"Interrupted","session":"scenario_20220727_091913_978","span":"interval","appname":"nosqlbench"},"details":{"command_line":"./activities/batch-producer\nsmall\n-v"}}
```

**Comment by yabinmeng** [comment]
Hi @mac89, `batch-msg-send-start` is a weird op that I should remove from this driver. By default Pulsar producer produces message in batch at the driver level. There are also config parameters to control the batching behavior.

I would recommend to use the regular msg-send op. I will find time to remove the "batch" operation

**Comment by mac89** [comment]
Ok, got it. I'll close this issue then.
