### ISSUE TITLE
cqld4 op template has error from unspecified missing value

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#808]
This should provide a better error, so the user knows what field was deemed required, but missing.

    3038 ERROR [main] ERRORHANDLER Error from driver or included library: java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:reusable-demo]  cause: NoSuchElementException:No value present No value present
java.util.concurrent.ExecutionException: java.lang.RuntimeException: javax.script.ScriptException: io.nosqlbench.api.errors.OpConfigError: Error while configuring op from workload template: [from:yaml:reusable-demo]  cause: NoSuchElementException:No value present No value present
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at io.nosqlbench.engine.core.script.ScenariosExecutor.getAsyncResultStatus(ScenariosExecutor.java:149)

**Comment by jshook** [comment]
fixed in latest merge
