### ISSUE TITLE
Grafana key missing creates NPE

### ISSUE THREAD

**Issue by msmygit** [nosqlbench/nosqlbench#862]
**Describe the bug**
When the Grafana api key is missing, we get the following NPE (`java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.statusCode()" because "response" is null`.

<details>
    <summary>NPE stacktrace</summary>

    $ java -version
    openjdk version "17.0.5" 2022-10-18
    OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu118.04)
    OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu118.04, mixed mode, sharing)
 
    stratperf@stratperf-nb-us-east4:~/keyvalue_cql$ cat logs/scenario_20221219_193111_857.log 	
    2022-12-19 19:31:12,258 [main] INFO : Configured scenario log at logs/scenario_20221219_193111_857.log
    2022-12-19 19:31:12,263 [main] INFO : Running NoSQLBench Version 4.17.31
    2022-12-19 19:31:12,263 [main] INFO : command-line: ./cql-keyvalue2 astra.main pooling=16:16:5000 keycount=10000000000L valuecount=10000000000L main-cycles=500m threads=40x userfile=../userfile.txt passfile=../passfile.txt secureconnectbundle=../secure-connect-db.zip protocol_version=v4 errors=counter --hdr-digits 4 --docker-metrics-at metrics --report-csv-to metrics -v --show-stacktraces
    2022-12-19 19:31:12,687 [main] INFO : client-hardware: {"if-speeds":["0Mib"],"physical-cores":"24","max-frequency-ghz":"0.00","logical-cores":"48","sockets":"2","memory-GiB":"188.89","processor-name":"Intel(R) Xeon(R) CPU @ 2.80GHz","heap-max-GiB":"29.97"}
    2022-12-19 19:31:13,316 [main] ERROR: internal error: Cannot invoke "java.net.http.HttpResponse.statusCode()" because "response" is null
    java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.statusCode()" because "response" is null
	    at io.nosqlbench.engine.clients.grafana.GrafanaClient.postApiTokenRequest(GrafanaClient.java:554) ~[nb5.jar:?]
	    at io.nosqlbench.engine.clients.grafana.GrafanaClient.createApiToken(GrafanaClient.java:515) ~[nb5.jar:?]
	    at io.nosqlbench.engine.clients.grafana.GrafanaClient.cacheApiToken(GrafanaClient.java:493) ~[nb5.jar:?]
	    at io.nosqlbench.engine.clients.grafana.annotator.GrafanaMetricsAnnotator.applyConfig(GrafanaMetricsAnnotator.java:162) ~[nb5.jar:?]
	    at io.nosqlbench.engine.core.annotation.Annotators.init(Annotators.java:82) ~[nb5.jar:?]
	    at io.nosqlbench.engine.cli.NBCLI.applyDirect(NBCLI.java:371) ~[nb5.jar:?]
	    at io.nosqlbench.engine.cli.NBCLI.apply(NBCLI.java:112) ~[nb5.jar:?]
	    at io.nosqlbench.engine.cli.NBCLI.main(NBCLI.java:92) ~[nb5.jar:?]
</details>

**To Reproduce**
1. Download the latest on a fresh machine
2. Try to run a workload without the Grafana api token/key with metrics sent to it with `--docker-metrics-at <ip/hostname>`

**What was Expected**
A clear and concise description of the error that an api token/key is missing.

**Additional context**
OS: Linux Ubuntu 18.04
environment: n/a
version info (`./nb --version` or `java -jar nb.jar --version`): `4.17.31`

**Screenshots, if applicable**

**Comment by jshook** [comment]
Closing this as it is for nb4
