### ISSUE TITLE
Sporadic test failures

### ISSUE THREAD

**Issue by jeffbanks** [nosqlbench/nosqlbench#913]
**Describe the bug**
The GHA build activity fails during test run, but succeeds after multiple attempts.

This appears to happen in the `engine-core` most of the time.

**To Reproduce**
1. Push changes triggering build activities.

**What was Expected**
When tests are run locally and fully passing, they should pass in GHA environment.

**Comment by jeffbanks** [comment]
More information added, appears to be related to this test typically.

```
Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.646 s <<< FAILURE! - in io.nosqlbench.engine.core.ActivityExecutorTest
Error:  io.nosqlbench.engine.core.ActivityExecutorTest.testNewActivityExecutor  Time elapsed: 0.106 s  <<< ERROR!
java.lang.RuntimeException: Invalid transition from Finished to Stopping
	at io.nosqlbench.engine.api.activityimpl.MotorState.enterState(MotorState.java:66)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.requestStop(CoreMotor.java:470)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityExecutor.reduceActiveMotorCountDownToThreadParam(ActivityExecutor.java:267)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityExecutor.adjustMotorCountToThreadParam(ActivityExecutor.java:243)
	at io.nosqlbench.engine.core.lifecycle.activity.ActivityExecutor.handleParameterMapUpdate(ActivityExecutor.java:211)
```
